export const IntentKeywordRegistry = {
  reuseBrief: {
    verb: /(?:再|一次|幫我|幫忙)?\s*(?:產生|生成|出|給我|做|產|跑)/u,
    digitCount: /(\d+)\s*(?:張|個|款|版|款式|個範例|個版本|張範例)/u,
    zhCount: /(兩|二|三|四|五|六|七|八|九|十)\s*(?:張|個|款|版|款式)/u,
    shortDigit: /(?:再|另外)\s*(\d+)\s*(?:張|個|款|版)/u,
    shortZh: /(?:再|另外)\s*(兩|二|三|四|五|六|七|八|九|十)\s*(?:張|個|款|版)/u,
    newVariant: /新\s*(?:的|版|款|一版|一個)/u,
    zhCountMap: {
      兩: 2,
      二: 2,
      三: 3,
      四: 4,
      五: 5,
      六: 6,
      七: 7,
      八: 8,
      九: 9,
      十: 10,
    } as Record<string, number>,
  },
  proceedBriefCues: [
    "先這樣做",
    "就先這樣",
    "先出一版",
    "先做看看",
    "直接做",
    "直接生成",
    "開始生成",
    "先產",
    "沒有要補充",
    "不用補充",
    "就這樣",
    "沒了",
    "差不多了",
    "可以了",
    "開始做",
    "先這樣",
    "不用了",
    "夠了",
    "不需要補充",
    "沒什麼要補的",
  ] as string[],
  quickActionChoiceWords:
    /你看|你選|你覺得|你直覺|你偏好|你想走|你想要|哪個比較|哪種比較|哪一個|想先看|想先試|比較喜歡|比較想|傾向/,
};

export default IntentKeywordRegistry;
