import { DesignTaskType } from "@prisma/client";
import type { DesignTaskField, DesignTaskSchema } from "./schema-registry";

const f = (
  key: string,
  label: string,
  group: string,
  question: string,
  required = true,
): DesignTaskField => ({
  key,
  label,
  group,
  question,
  required,
  kind:
    !required
      ? "optional"
      : key === "assetQuality" || group === "asset_validation"
        ? "asset_validation"
        : group === "quote"
          ? "quote"
          : "core",
  blockingForReady: required,
  canInferFromContext: ["brandName", "companyName", "industry", "website", "logoFile", "brandColor", "brandFont"].includes(key),
  askStrategy:
    ["stylePreference", "brandPersonality", "targetAudience", "purpose", "usageScenario", "orientation", "doubleSided"].includes(key)
      ? "example_choice"
      : ["brandName", "companyName", "industry", "website", "logoFile", "brandColor", "brandFont"].includes(key)
        ? "confirm_from_context"
        : "direct",
});

export const DEFAULT_DESIGN_TASK_SCHEMAS: Record<DesignTaskType, DesignTaskSchema> = {
  [DesignTaskType.logo]: {
    taskType: DesignTaskType.logo,
    displayName: "品牌Logo設計",
    description: "收集品牌名稱、產業、理念、風格、使用場景，以及是否延伸 VI / 品牌標準手冊。",
    keywords: ["logo", "品牌logo", "品牌標誌", "商標", "標誌設計"],
    starters: ["品牌Logo設計", "我想做 Logo", "需要品牌標誌"],
    sharedContextKeys: ["companyName", "brandName", "industry", "website"],
    fields: [
      f("brandName", "品牌名稱", "basic", "品牌完整名稱是什麼？中文、英文、縮寫如果有都可以一起告訴我。"),
      f("autoFillCompanyInfo", "公司資料帶入", "basic", "如果已有公司資料，我可以一起帶入。你希望品牌名稱直接沿用公司名稱嗎？", false),
      f("industry", "品牌產業", "basic", "品牌或公司屬於什麼產業？例如餐飲、醫療、美妝、科技。"),
      f("brandPhilosophy", "品牌理念", "basic", "品牌想傳達的核心價值與理念是什麼？"),
      f("brandPersonality", "品牌個性", "basic", "品牌希望給人的感覺是什麼？例如專業、活潑、溫暖、科技感、高端。"),
      f("targetAudience", "目標客群", "basic", "主要目標客群是誰？例如年齡層、性別、消費族群。"),
      f("competitorBrands", "競爭品牌", "basic", "同產業或競爭品牌有哪些？", false),
      f("stylePreference", "喜歡的風格", "style", "Logo 想走什麼風格？例如簡約、日系、科技感、插畫風、奢華風。"),
      f("referenceCases", "參考案例", "style", "有沒有喜歡或不喜歡的 Logo 案例可以參考？", false),
      f("colorPreference", "顏色偏好", "style", "希望使用或避免哪些顏色？", false),
      f("usageScenarios", "使用場景", "usage", "Logo 之後會使用在哪些地方？例如名片、網站、招牌、包裝。"),
      f("extendToAssets", "延伸製作物", "usage", "若要延伸到其他製作物，這次預計延伸到哪些項目？例如名片、DM、包裝。", false),
      f("needVI", "品牌識別系統", "quote", "除了 Logo，本次是否也需要品牌識別系統（VI）？", false),
      f("needBrandGuideline", "品牌標準手冊", "quote", "是否也需要品牌標準手冊？這會影響報價。", false),
    ],
  },
  [DesignTaskType.vi]: {
    taskType: DesignTaskType.vi,
    displayName: "品牌識別系統（VI）",
    description: "收集品牌識別系統的延伸項目、使用情境與整體視覺規範需求。",
    keywords: ["vi", "品牌識別", "識別系統", "視覺識別"],
    starters: ["品牌識別系統", "VI 設計"],
    fields: [
      f("brandAssets", "既有品牌資產", "basic", "目前有哪些既有品牌資產可以延伸？例如 Logo、色票、字體。"),
      f("applicationItems", "延伸應用項目", "basic", "這次 VI 需要延伸到哪些應用項目？"),
      f("styleDirection", "整體風格方向", "style", "品牌識別系統想呈現什麼風格方向？"),
      f("usageScenario", "使用情境", "usage", "這套識別系統主要會使用在哪些情境？"),
    ],
  },
  [DesignTaskType.brand_guideline]: {
    taskType: DesignTaskType.brand_guideline,
    displayName: "品牌標準手冊",
    description: "收集品牌手冊用途、需收錄內容與交付格式。",
    keywords: ["品牌手冊", "品牌標準手冊", "guideline", "品牌規範"],
    starters: ["品牌標準手冊", "品牌規範手冊"],
    fields: [
      f("manualPurpose", "手冊用途", "basic", "這份品牌手冊主要是內部使用、外部合作，還是兩者都要？"),
      f("includedAssets", "收錄內容", "basic", "手冊裡預計收錄哪些品牌資產與規範？"),
      f("deliveryFormat", "交付格式", "delivery", "希望交付成 PDF、可編輯檔，還是兩者都要？"),
    ],
  },
  [DesignTaskType.business_card]: {
    taskType: DesignTaskType.business_card,
    displayName: "名片設計",
    description: "收集名片基本資訊、品牌資訊、設計內容、尺寸與印刷交付需求。",
    keywords: ["名片", "business card", "卡片設計"],
    starters: ["名片設計", "公司名片設計"],
    sharedContextKeys: ["brandName", "companyName", "website", "logoFile", "brandColor", "brandFont"],
    fields: [
      f("companyName", "公司名稱", "basic", "名片上需要呈現的公司或品牌名稱是什麼？"),
      f("personName", "姓名", "basic", "名片持有人的姓名是什麼？需要中英文嗎？"),
      f("jobTitle", "職稱", "basic", "職稱要顯示什麼？例如總經理、設計師、業務。"),
      f("phone", "聯絡電話", "basic", "名片上的聯絡電話是什麼？"),
      f("email", "電子郵件", "basic", "名片上的電子郵件要放哪一個？"),
      f("address", "公司地址", "basic", "名片上要放哪個公司或門市地址？", false),
      f("website", "官方網站", "basic", "是否需要放品牌網站或公司官網？如果要，網址是什麼？", false),
      f("socialAccounts", "社群帳號", "basic", "是否需要放 IG、Facebook、LINE 等社群資訊？", false),
      f("logoFile", "Logo檔案", "brand", "是否已提供品牌 Logo 檔案？", false),
      f("brandColor", "品牌顏色", "brand", "是否有指定品牌顏色？", false),
      f("brandFont", "品牌字體", "brand", "是否有指定品牌字體？", false),
      f("brandStyle", "品牌風格", "brand", "名片整體風格想呈現什麼感覺？例如簡約、科技、高端、活潑。"),
      f("cardLanguage", "名片語言", "design", "名片需要中文、英文，還是中英文雙語版本？"),
      f("doubleSided", "名片正反面", "design", "名片想做單面還是雙面？"),
      f("qrCode", "QR Code", "design", "是否需要加入 QR Code？例如 LINE 或網站。", false),
      f("graphics", "圖片或圖形", "design", "是否需要放照片或品牌圖形元素？", false),
      f("specialInfo", "特殊資訊", "design", "是否需要放營業時間、服務項目等特殊資訊？", false),
      f("cardSize", "名片尺寸", "layout", "名片尺寸是否使用常見尺寸，例如 90×54mm？"),
      f("orientation", "名片方向", "layout", "名片要橫式還是直式設計？"),
      f("layoutRequirement", "排版需求", "layout", "有沒有特別排版需求？", false),
      f("printRequired", "是否需要印刷", "print", "這次名片設計需要協助印刷嗎？", false),
      f("printQuantity", "印刷數量", "print", "預計印刷多少張？", false),
      f("paperMaterial", "紙張材質", "print", "有指定紙張材質嗎？例如銅版紙、象牙卡。", false),
      f("specialFinishing", "特殊加工", "print", "是否需要上膜、局部上光、燙金等特殊加工？", false),
      f("useDate", "使用時間", "delivery", "名片預計什麼時候要使用？", false),
      f("deadline", "交稿期限", "delivery", "需要完成設計的時間是什麼時候？", false),
      f("fileFormat", "檔案格式", "delivery", "需要可編輯原始檔、印刷完稿檔，還是兩者都要？", false),
      f("assetQuality", "素材檔案品質", "delivery", "如果有提供 Logo 或圖檔，請一併確認是否為可編輯檔或解析度足夠印刷。", false),
    ],
  },
  [DesignTaskType.dm]: {
    taskType: DesignTaskType.dm,
    displayName: "DM設計／傳單設計",
    description: "收集 DM 基本資訊、內容、素材、風格、尺寸版型、印刷與交付需求。",
    keywords: ["dm", "傳單", "宣傳單", "摺頁", "dm設計"],
    starters: ["DM設計", "傳單設計"],
    sharedContextKeys: ["brandName", "companyName", "website", "contactInfo", "logoFile"],
    fields: [
      f("companyName", "公司或品牌名稱", "basic", "DM 所屬品牌或公司名稱是什麼？"),
      f("contactInfo", "聯絡資訊", "basic", "需要放在 DM 上的電話、地址、網站、社群帳號有哪些？"),
      f("purpose", "用途", "basic", "這份 DM 主要用途是什麼？例如活動宣傳、產品介紹、開幕宣傳、優惠活動。"),
      f("deliveryMethod", "發放方式", "basic", "DM 是要實體發放、郵寄、店面擺放，還是數位使用？"),
      f("headline", "主標題", "content", "DM 最主要的標題文字想放什麼？"),
      f("mainContent", "主要內容", "content", "需要放在 DM 上的主要文字內容有哪些？"),
      f("productInfo", "商品或服務資訊", "content", "這次要介紹哪些產品或服務？"),
      f("eventInfo", "活動資訊", "content", "是否有活動時間、優惠內容或折扣資訊？", false),
      f("messagePriority", "重要訊息排序", "content", "哪些資訊是最重要、需要優先強調的？", false),
      f("imageAssets", "圖片素材", "assets", "是否有提供產品照片或圖片素材？", false),
      f("logoFile", "Logo檔案", "assets", "品牌 Logo 是否已提供？", false),
      f("illustrationNeed", "插圖需求", "assets", "是否需要設計插圖或圖示？", false),
      f("qrCode", "QR Code", "assets", "是否需要放 QR Code，例如 LINE、網站或活動報名？", false),
      f("stylePreference", "設計風格", "style", "希望 DM 呈現什麼風格？例如簡約、活潑、日系、高端。"),
      f("colorPreference", "顏色偏好", "style", "是否有指定品牌顏色或避免的顏色？", false),
      f("referenceCases", "參考案例", "style", "是否有喜歡的 DM 設計參考？", false),
      f("dmSize", "DM尺寸", "layout", "DM 有指定尺寸嗎？例如 A4、A5、A6。"),
      f("formatType", "版型形式", "layout", "是單面還是雙面設計？"),
      f("foldRequirement", "摺頁需求", "layout", "是否需要對摺或三摺設計？", false),
      f("printRequired", "是否需要印刷", "print", "這次 DM 設計需要協助印刷嗎？", false),
      f("printQuantity", "印刷數量", "print", "預計印刷多少份？", false),
      f("paperMaterial", "紙張材質", "print", "有指定紙張材質嗎？例如銅版紙、象牙卡。", false),
      f("specialFinishing", "特殊加工", "print", "是否需要上膜、局部上光、燙金等特殊加工？", false),
      f("useDate", "使用時間", "delivery", "DM 預計何時要使用？", false),
      f("deadline", "交稿期限", "delivery", "需要完成設計的時間是什麼時候？", false),
      f("fileFormat", "檔案格式", "delivery", "需要可編輯原始檔或印刷完稿檔嗎？", false),
      f("assetQuality", "素材檔案品質", "delivery", "如有提供 Logo 或圖檔，請確認是否為可編輯檔或解析度足夠印刷。", false),
    ],
  },
  [DesignTaskType.poster]: {
    taskType: DesignTaskType.poster,
    displayName: "海報設計",
    description: "收集海報基本資訊、內容、素材、風格、尺寸與印刷交付需求。",
    keywords: ["海報", "poster", "活動海報"],
    starters: ["海報設計"],
    fields: [
      f("companyName", "公司或品牌名稱", "basic", "海報所屬品牌或公司名稱是什麼？"),
      f("contactInfo", "聯絡資訊", "basic", "海報上需要放的聯絡資訊有哪些？", false),
      f("purpose", "用途", "basic", "海報主要用途是什麼？例如活動宣傳、產品宣傳、招生宣傳、活動公告。"),
      f("postingLocation", "張貼地點", "basic", "海報會張貼在哪裡？例如店面、商場、學校、展場、戶外。"),
      f("headline", "主標題", "content", "海報主標題想放什麼？"),
      f("mainContent", "主要內容", "content", "海報需要呈現哪些主要內容？"),
      f("productInfo", "商品或服務資訊", "content", "要介紹哪些商品或服務？", false),
      f("eventInfo", "活動資訊", "content", "是否有活動時間、優惠內容或折扣資訊？", false),
      f("messagePriority", "重要訊息排序", "content", "哪些資訊是最重要、需要優先強調的？", false),
      f("imageAssets", "圖片素材", "assets", "是否有提供產品照片或圖片素材？", false),
      f("logoFile", "Logo檔案", "assets", "品牌 Logo 是否已提供？", false),
      f("illustrationNeed", "插圖需求", "assets", "是否需要設計插圖或圖示？", false),
      f("qrCode", "QR Code", "assets", "是否需要放 QR Code？", false),
      f("stylePreference", "設計風格", "style", "希望海報呈現什麼風格？"),
      f("colorPreference", "顏色偏好", "style", "是否有指定品牌顏色或避免的顏色？", false),
      f("referenceCases", "參考案例", "style", "是否有喜歡的海報設計參考？", false),
      f("posterSize", "海報尺寸", "layout", "海報尺寸有指定嗎？例如 A4、A5、A6。"),
      f("formatType", "版型形式", "layout", "海報是單面還是雙面？", false),
      f("foldRequirement", "摺頁需求", "layout", "是否需要對摺或三摺？", false),
      f("printRequired", "是否需要印刷", "print", "這次海報設計需要協助印刷嗎？", false),
      f("printQuantity", "印刷數量", "print", "預計印刷多少份？", false),
      f("paperMaterial", "紙張材質", "print", "有指定紙張材質嗎？", false),
      f("specialFinishing", "特殊加工", "print", "是否需要上膜、局部上光、燙金等加工？", false),
      f("useDate", "使用時間", "delivery", "海報預計何時要使用？", false),
      f("deadline", "交稿期限", "delivery", "海報需要完成的時間是什麼時候？", false),
      f("fileFormat", "檔案格式", "delivery", "需要可編輯檔或印刷完稿檔嗎？", false),
      f("assetQuality", "素材檔案品質", "delivery", "如有提供 Logo 或圖檔，請確認是否為可編輯檔或解析度足夠印刷。", false),
    ],
  },
  [DesignTaskType.catalog]: {
    taskType: DesignTaskType.catalog,
    displayName: "型錄設計",
    description: "收集型錄用途、產品資訊、風格、印刷、頁數與裝訂需求。",
    keywords: ["型錄", "catalog", "目錄", "產品型錄"],
    starters: ["型錄設計"],
    fields: [
      f("companyName", "公司或品牌名稱", "basic", "型錄所屬品牌或公司名稱是什麼？"),
      f("catalogPurpose", "型錄用途", "basic", "型錄主要用途是什麼？例如產品介紹、業務銷售、展覽使用、招商介紹。"),
      f("usageScenario", "使用場景", "basic", "型錄會在哪裡使用？例如門市、展覽、業務拜訪、郵寄給客戶。"),
      f("targetAudience", "目標客群", "basic", "型錄主要給誰看？例如消費者、經銷商、企業客戶。"),
      f("companyIntro", "公司介紹", "content", "是否需要放公司簡介或品牌故事？", false),
      f("productInfo", "產品資訊", "content", "需要放入型錄的產品名稱、規格、介紹內容有哪些？"),
      f("productCategories", "產品分類", "content", "產品是否需要依類別分類呈現？", false),
      f("priceInfo", "價格資訊", "content", "是否需要放產品價格或報價資訊？", false),
      f("contactInfo", "聯絡資訊", "content", "型錄上需要放哪些聯絡資訊？", false),
      f("socialInfo", "社群資訊", "content", "是否需要放社群帳號或 QR Code？", false),
      f("specialInfo", "特別資訊", "content", "是否有產品特色、使用方式、注意事項等特別資訊？", false),
      f("productPhotos", "產品照片", "assets", "是否提供產品照片？", false),
      f("logoFile", "Logo檔案", "assets", "品牌 Logo 是否提供？", false),
      f("illustrations", "圖示或插圖", "assets", "是否需要圖示、插圖或資訊圖表？", false),
      f("imageStyle", "圖片風格", "assets", "產品照片是否需要統一風格或背景？", false),
      f("stylePreference", "整體風格", "style", "希望型錄呈現什麼風格？例如簡約、科技、高端、日系。"),
      f("colorPreference", "顏色偏好", "style", "是否有品牌指定顏色？", false),
      f("fontRequirement", "字體需求", "style", "是否有指定品牌字體？", false),
      f("referenceCases", "參考案例", "style", "是否有喜歡或不喜歡的型錄設計？", false),
      f("printRequired", "是否需要印刷", "print", "這次型錄設計需要協助印刷嗎？", false),
      f("printQuantity", "印刷數量", "print", "預計印刷多少本？", false),
      f("paperMaterial", "紙張材質", "print", "有指定紙張材質嗎？", false),
      f("specialFinishing", "特殊加工", "print", "是否需要上膜、局部上光、燙金等加工？", false),
      f("useDate", "使用時間", "delivery", "型錄預計何時要使用？", false),
      f("deadline", "交稿期限", "delivery", "設計需要完成的時間是什麼時候？", false),
      f("fileFormat", "檔案格式", "delivery", "需要可編輯原始檔或印刷完稿檔嗎？", false),
      f("pageCount", "預計頁數", "layout", "型錄大約幾頁？"),
      f("productCount", "產品數量", "layout", "這次型錄要放多少個產品？"),
      f("layoutRequirement", "版型需求", "layout", "是否需要跨頁設計或特殊排版？", false),
      f("languageVersions", "語言版本", "layout", "是否需要中英文或多語版本？", false),
      f("catalogSize", "型錄尺寸", "layout", "型錄尺寸是 A4、A5 還是其他尺寸？"),
      f("orientation", "型錄方向", "layout", "型錄要直式還是橫式？", false),
      f("bindingMethod", "裝訂方式", "layout", "希望怎麼裝訂？例如騎馬釘、膠裝、線裝。", false),
      f("assetQuality", "素材檔案品質", "delivery", "如有提供 Logo 或圖檔，請確認是否為可編輯檔或解析度足夠印刷。", false),
    ],
  },
  [DesignTaskType.menu]: {
    taskType: DesignTaskType.menu,
    displayName: "菜單設計",
    description: "收集菜單用途、餐點內容、風格、版面、印刷與文案優化需求。",
    keywords: ["菜單", "menu", "餐廳菜單"],
    starters: ["菜單設計"],
    fields: [
      f("brandName", "店名或品牌名稱", "basic", "餐廳或品牌名稱是什麼？"),
      f("restaurantType", "餐廳類型", "basic", "餐廳屬於哪種類型？例如咖啡廳、餐廳、酒吧、甜點店。"),
      f("menuPurpose", "菜單用途", "basic", "菜單主要用途是內用、外帶、桌上還是牆面展示？"),
      f("usageScenario", "使用場景", "basic", "菜單會在哪裡使用？例如店內桌上、櫃台、戶外展示。"),
      f("targetAudience", "目標客群", "basic", "餐廳主要客群是誰？例如家庭、年輕人、商務客。"),
      f("dishNames", "菜品名稱", "content", "所有需要放入菜單的餐點名稱有哪些？"),
      f("dishCategories", "菜品分類", "content", "餐點分類有哪些？例如主餐、飲料、甜點、前菜。"),
      f("pricing", "價格資訊", "content", "每個餐點的價格資訊有整理好了嗎？"),
      f("dishDescriptions", "菜品介紹", "content", "是否需要簡短描述或介紹？", false),
      f("recommendationMarks", "推薦標示", "content", "是否需要標示人氣商品或推薦菜色？", false),
      f("comboInfo", "套餐資訊", "content", "是否有套餐或組合餐？", false),
      f("specialMarks", "特別標示", "content", "是否需要標示辣度、素食、過敏資訊等？", false),
      f("dishPhotos", "菜品照片", "assets", "是否提供餐點照片？", false),
      f("logoFile", "Logo檔案", "assets", "餐廳 Logo 是否提供？", false),
      f("menuStyle", "菜單風格", "style", "希望菜單呈現什麼風格？例如日系、簡約、復古、高端。"),
      f("brandColor", "品牌顏色", "style", "是否有指定品牌顏色？", false),
      f("fontStyle", "字體風格", "style", "是否有指定字體或字體風格？", false),
      f("referenceCases", "參考案例", "style", "是否有喜歡或不喜歡的菜單設計？", false),
      f("pageCount", "預計頁數", "layout", "菜單大約幾頁？"),
      f("layoutRequirement", "版型需求", "layout", "是否需要跨頁設計或特殊排版？", false),
      f("languageVersions", "語言版本", "layout", "是否需要中英文或多語版本？", false),
      f("menuSize", "菜單尺寸", "layout", "菜單尺寸希望用 A4、A3、A5 還是其他？"),
      f("orientation", "菜單方向", "layout", "菜單要橫式還是直式？", false),
      f("bindingMethod", "裝訂方式", "layout", "希望怎麼裝訂？例如騎馬釘、膠裝、單張、桌卡。", false),
      f("waterproofMaterial", "防水或耐用材質", "layout", "是否需要防水或耐用材質，例如護貝或 PVC？", false),
      f("printRequired", "是否需要印刷", "print", "這次菜單設計需要協助印刷嗎？", false),
      f("printQuantity", "印刷數量", "print", "預計印刷多少份？", false),
      f("paperMaterial", "紙張材質", "print", "有指定紙張材質嗎？", false),
      f("specialFinishing", "特殊加工", "print", "是否需要上膜、局部上光、燙金等加工？", false),
      f("useDate", "使用時間", "delivery", "菜單預計何時要使用？", false),
      f("deadline", "交稿期限", "delivery", "設計需要完成的時間是什麼時候？", false),
      f("fileFormat", "檔案格式", "delivery", "需要印刷完稿檔或可編輯原始檔嗎？", false),
      f("sloganByPage", "每頁Slogan", "copywriting", "是否需要每個分類或頁面的主標語？", false),
      f("itemCopy", "品項介紹文字", "copywriting", "是否需要協助撰寫餐點描述與賣點文字？", false),
      f("brandStory", "品牌故事簡述", "copywriting", "是否需要加入餐廳理念或品牌故事？", false),
      f("signatureDishStory", "招牌料理介紹", "copywriting", "是否需要招牌料理的故事或特色說明？", false),
      f("ingredientStory", "食材特色說明", "copywriting", "是否需要說明產地、手工製作或特色食材？", false),
    ],
  },
  [DesignTaskType.invitation_card]: {
    taskType: DesignTaskType.invitation_card,
    displayName: "邀請卡設計",
    description: "收集活動資訊、邀請對象、卡片形式、印刷加工與交付需求。",
    keywords: ["邀請卡", "invitation", "喜帖", "卡片邀請"],
    starters: ["邀請卡設計"],
    fields: [
      f("eventName", "活動名稱", "basic", "這次邀請卡是什麼活動？例如婚禮、開幕、品牌發表會。"),
      f("eventDate", "活動日期", "basic", "活動日期是什麼時候？"),
      f("eventTime", "活動時間", "basic", "活動開始與結束時間是什麼？"),
      f("eventLocation", "活動地點", "basic", "活動舉辦地址或場地名稱是什麼？"),
      f("organizer", "主辦單位", "basic", "主辦人或品牌名稱是什麼？"),
      f("invitees", "邀請對象", "invitees", "主要邀請對象是誰？例如親友、客戶、VIP、員工。"),
      f("titleNeed", "稱謂需求", "invitees", "是否需要稱謂，例如先生、小姐、貴賓？", false),
      f("customNameNeed", "客製姓名", "invitees", "是否需要每張卡片客製姓名？", false),
      f("headline", "主標題", "content", "邀請卡主標題想放什麼？"),
      f("inviteContent", "邀請內文", "content", "邀請卡內文或邀請詞是什麼？"),
      f("eventContent", "活動資訊內容", "content", "日期、時間、地點等資訊要如何呈現？"),
      f("contactMethod", "聯絡方式", "content", "是否需要放聯絡電話或報名方式？", false),
      f("qrCode", "QR Code", "content", "是否需要放報名或地圖 QR Code？", false),
      f("stylePreference", "設計風格", "style", "希望邀請卡呈現什麼風格？例如典雅、浪漫、簡約、奢華。"),
      f("colorPreference", "顏色偏好", "style", "是否有指定顏色或品牌色？", false),
      f("referenceCases", "參考案例", "style", "是否有喜歡或不喜歡的邀請卡風格？", false),
      f("illustrationNeed", "插圖或圖騰", "style", "是否需要花紋、圖案或插畫？", false),
      f("cardSize", "卡片尺寸", "layout", "邀請卡尺寸是 A6、方形還是客製尺寸？"),
      f("orientation", "卡片方向", "layout", "邀請卡要橫式還是直式？", false),
      f("cardFormat", "單張或摺卡", "layout", "要做單張卡片還是對摺卡？"),
      f("envelopeNeed", "是否需要信封", "layout", "是否需要搭配信封？", false),
      f("waxSealNeed", "封蠟或貼紙", "layout", "是否需要封蠟或特殊裝飾貼紙？", false),
      f("printQuantity", "印刷數量", "print", "預計印刷張數是多少？", false),
      f("paperMaterial", "紙張材質", "print", "紙張材質有指定嗎？例如美術紙、象牙卡、厚卡紙。", false),
      f("surfaceFinishing", "表面加工", "print", "是否需要燙金、燙銀、壓紋、局部上光等加工？", false),
      f("specialShape", "特殊造型", "print", "是否需要圓角或特殊形狀裁切？", false),
      f("useDate", "使用時間", "delivery", "邀請卡何時需要使用？", false),
      f("deadline", "交稿期限", "delivery", "設計需要完成的時間是什麼時候？", false),
      f("printRequired", "是否需要印刷", "delivery", "是否需要協助印刷？", false),
      f("fileFormat", "檔案需求", "delivery", "需要電子版或印刷完稿檔嗎？", false),
      f("assetQuality", "素材檔案品質", "delivery", "如有提供 Logo 或圖檔，請確認是否為可編輯檔或解析度足夠印刷。", false),
    ],
  },
  [DesignTaskType.sticker]: {
    taskType: DesignTaskType.sticker,
    displayName: "貼紙設計",
    description: "收集貼紙用途、內容、形式、材質與印刷交付需求。",
    keywords: ["貼紙", "sticker", "標籤貼紙", "產品貼紙"],
    starters: ["貼紙設計"],
    fields: [
      f("purpose", "用途", "basic", "貼紙主要用途是什麼？例如產品標籤、包裝貼紙、活動貼紙、品牌貼紙。"),
      f("usageScenario", "使用場景", "basic", "貼紙會貼在哪裡？例如產品包裝、瓶身、盒子、紙袋。"),
      f("brandDisplay", "品牌名稱或Logo", "basic", "貼紙上是否需要放品牌名稱或品牌 Logo？"),
      f("stickerContent", "貼紙內容", "basic", "貼紙需要呈現哪些文字或資訊？"),
      f("regulationInfo", "法規資訊", "basic", "若為產品貼紙，是否需要放成分、容量、保存期限等資訊？", false),
      f("mainText", "主要文字", "content", "貼紙上最重要的文字內容是什麼？"),
      f("productInfo", "產品資訊", "content", "是否需要產品名稱、規格或說明？", false),
      f("barcodeNeed", "條碼需求", "content", "是否需要放條碼或商品條碼？", false),
      f("qrCode", "QR Code", "content", "是否需要放網站或活動 QR Code？", false),
      f("iconNeed", "圖示需求", "content", "是否需要圖示、標章或認證標誌？", false),
      f("logoFile", "Logo檔案", "assets", "品牌 Logo 是否提供？", false),
      f("productImage", "產品圖片", "assets", "是否需要放產品圖片？", false),
      f("illustrationNeed", "插圖需求", "assets", "是否需要插畫或裝飾圖案？", false),
      f("brandGraphicElements", "品牌圖形元素", "assets", "是否有品牌圖騰或視覺元素？", false),
      f("stylePreference", "設計風格", "style", "希望貼紙呈現什麼風格？例如簡約、可愛、日系、高端。"),
      f("colorPreference", "顏色偏好", "style", "是否有品牌指定顏色？", false),
      f("referenceCases", "參考案例", "style", "是否有喜歡或不喜歡的貼紙設計？", false),
      f("brandTone", "品牌調性", "style", "貼紙希望呈現什麼品牌形象？", false),
      f("stickerSize", "貼紙尺寸", "layout", "貼紙大小是多少？例如 5cm、10cm 或客製尺寸。"),
      f("stickerShape", "貼紙形狀", "layout", "是圓形、方形、橢圓形還是特殊造型？"),
      f("printQuantity", "貼紙數量", "layout", "預計印刷多少張？", false),
      f("sheetOrSingle", "單張或整版", "layout", "需要整版貼紙還是單張貼紙？", false),
      f("dieCutNeed", "是否需要裁型", "layout", "是否需要刀模裁切特殊形狀？", false),
      f("material", "貼紙材質", "print", "有指定貼紙材質嗎？例如銅版貼紙、透明貼紙、防水貼紙。", false),
      f("surfaceFinishing", "表面加工", "print", "是否需要亮膜、霧膜或特殊加工？", false),
      f("waterproofNeed", "是否需要防水", "print", "是否需要防水或耐磨材質？", false),
      f("specialEffect", "特殊效果", "print", "是否需要燙金、燙銀、局部上光等特殊效果？", false),
      f("useDate", "使用時間", "delivery", "貼紙預計何時需要使用？", false),
      f("deadline", "交稿期限", "delivery", "設計需要完成的時間是什麼時候？", false),
      f("printRequired", "是否需要印刷", "delivery", "是否需要協助印刷？", false),
      f("fileFormat", "檔案需求", "delivery", "需要印刷完稿檔或可編輯原始檔嗎？", false),
      f("assetQuality", "素材檔案品質", "delivery", "如有提供 Logo 或圖檔，請確認是否為可編輯檔或解析度足夠印刷。", false),
    ],
  },
  [DesignTaskType.packaging]: {
    taskType: DesignTaskType.packaging,
    displayName: "產品包裝設計",
    description: "收集產品資訊、包裝內容、形式、風格、印刷與交付需求。",
    keywords: ["包裝", "包裝設計", "產品包裝", "禮盒", "盒裝設計"],
    starters: ["包裝設計", "產品包裝設計"],
    sharedContextKeys: ["brandName", "logoFile", "brandColor", "website"],
    fields: [
      f("brandName", "品牌名稱", "basic", "品牌或公司名稱是什麼？"),
      f("productName", "產品名稱", "basic", "產品名稱或系列名稱是什麼？"),
      f("productType", "產品類型", "basic", "產品種類是什麼？例如食品、保養品、飲料、禮盒。"),
      f("productPurpose", "產品用途", "basic", "產品主要用途或功能是什麼？"),
      f("targetAudience", "目標客群", "basic", "主要消費族群是誰？例如女性、年輕族群、商務客。"),
      f("productSpecs", "產品規格", "product", "產品容量、重量或尺寸是多少？"),
      f("productIngredients", "產品成分", "product", "是否需要標示產品成分或原料？", false),
      f("storageInfo", "保存資訊", "product", "是否需要標示保存期限或保存方式？", false),
      f("usageInstruction", "使用方式", "product", "是否需要標示產品使用方法？", false),
      f("originInfo", "產地資訊", "product", "是否需要標示產地或製造商資訊？", false),
      f("panelContent", "包裝每面資訊", "content", "請清楚確認包裝盒每一面需要擺放哪些資訊。"),
      f("brandLogo", "品牌Logo", "content", "品牌 Logo 是否提供？", false),
      f("productDescription", "產品說明", "content", "是否需要產品介紹或賣點說明？", false),
      f("certificationMarks", "標章資訊", "content", "是否需要放認證標章或相關標誌？", false),
      f("barcodeNeed", "條碼需求", "content", "是否需要商品條碼？", false),
      f("qrCode", "QR Code", "content", "是否需要放網站或品牌 QR Code？", false),
      f("packageType", "包裝類型", "layout", "包裝類型是紙盒、禮盒、袋裝還是瓶身標籤？"),
      f("packageSize", "包裝尺寸", "layout", "包裝盒或包裝袋的尺寸是多少？"),
      f("packageStructure", "包裝結構", "layout", "是否已有刀模或包裝結構？", false),
      f("packageQuantity", "包裝數量", "layout", "一個包裝內包含幾個產品？", false),
      f("innerPackageNeed", "是否需要內包裝", "layout", "是否需要設計內盒或內襯？", false),
      f("stylePreference", "設計風格", "style", "希望包裝呈現什麼風格？例如簡約、日系、高端、自然。"),
      f("colorPreference", "顏色偏好", "style", "是否有指定品牌顏色？", false),
      f("brandTone", "品牌調性", "style", "品牌希望呈現什麼形象？例如健康、奢華、年輕。"),
      f("referenceCases", "參考案例", "style", "是否有喜歡或不喜歡的包裝設計？", false),
      f("illustrationNeed", "插圖需求", "style", "是否需要插畫或品牌圖騰？", false),
      f("printMethod", "印刷方式", "print", "是否有指定印刷方式？", false),
      f("paperMaterial", "紙張材質", "print", "有指定紙張材質嗎？例如銅版紙、美術紙、卡紙。", false),
      f("surfaceFinishing", "表面加工", "print", "是否需要燙金、燙銀、局部上光、壓紋等加工？", false),
      f("specialEffect", "特殊效果", "print", "是否需要特殊工藝或材質？", false),
      f("proofNeed", "是否需要打樣", "print", "是否需要印刷打樣確認？", false),
      f("useDate", "使用時間", "delivery", "包裝預計何時需要使用？", false),
      f("deadline", "交稿期限", "delivery", "設計需要完成的時間是什麼時候？", false),
      f("printRequired", "是否需要印刷", "delivery", "是否需要協助印刷？", false),
      f("fileFormat", "檔案需求", "delivery", "需要印刷完稿檔或可編輯原始檔嗎？", false),
    ],
  },
  [DesignTaskType.social_post]: {
    taskType: DesignTaskType.social_post,
    displayName: "社群貼文設計",
    description: "收集社群貼文設計與文案撰寫需求、平台、主題、形式與導流目標。",
    keywords: ["社群貼文", "貼文", "社群設計", "instagram", "facebook", "threads", "文案"],
    starters: ["社群貼文設計", "貼文文案怎麼寫", "社群文案怎麼寫"],
    sharedContextKeys: ["brandName", "industry", "socialAccounts", "website", "logoFile"],
    fields: [
      f("brandName", "品牌名稱", "basic", "品牌或公司名稱是什麼？"),
      f("industry", "品牌產業", "basic", "品牌屬於什麼產業？例如餐飲、美妝、醫療、教育。"),
      f("platforms", "社群平台", "basic", "這次貼文需要發布在哪些平台？例如 Instagram、Facebook、LINE、Threads。"),
      f("socialAccounts", "社群帳號", "basic", "品牌社群帳號名稱或網址是什麼？", false),
      f("purpose", "貼文目的", "basic", "貼文主要目的是品牌曝光、活動宣傳還是產品介紹？"),
      f("topic", "貼文主題", "content", "本次貼文想傳達的主題是什麼？"),
      f("postCount", "貼文數量", "content", "本次需要設計幾張貼文？"),
      f("copywritingNeed", "貼文文字", "content", "是否需要一併撰寫貼文文案？", false),
      f("productInfo", "產品或服務資訊", "content", "貼文需要介紹哪些產品或服務？", false),
      f("eventInfo", "活動資訊", "content", "是否有活動內容需要宣傳？", false),
      f("keyMessage", "關鍵訊息", "content", "這次貼文最希望傳達的重點是什麼？"),
      f("logoFile", "Logo檔案", "assets", "品牌 Logo 是否提供？", false),
      f("productPhotos", "產品照片", "assets", "是否提供產品或服務照片？", false),
      f("brandAssets", "品牌素材", "assets", "是否有品牌圖形、圖示或其他素材？", false),
      f("imageStyle", "圖片風格", "assets", "照片是否有統一風格或視覺方向？", false),
      f("stylePreference", "設計風格", "style", "希望貼文呈現什麼風格？例如簡約、活潑、日系、高端。"),
      f("brandColor", "品牌顏色", "style", "是否有指定品牌顏色？", false),
      f("brandFont", "品牌字體", "style", "是否有指定品牌字體？", false),
      f("referenceCases", "參考案例", "style", "是否有喜歡或不喜歡的社群貼文風格？", false),
      f("postSize", "貼文尺寸", "layout", "貼文尺寸是正方形、直式還是橫式？"),
      f("postFormat", "貼文形式", "layout", "這次是單張貼文還是多張輪播貼文？"),
      f("coverNeed", "是否需要封面", "layout", "如果是輪播貼文，是否需要封面設計？", false),
      f("publishTime", "發布時間", "delivery", "貼文預計什麼時候發布？", false),
      f("publishFrequency", "發布頻率", "delivery", "是否有固定發布頻率，例如每週或每月？", false),
      f("fileFormat", "檔案需求", "delivery", "需要可編輯檔或圖片檔嗎？", false),
      f("postingHelp", "是否需要代發", "delivery", "是否需要協助發布貼文？", false),
      f("primaryMessage", "主要訊息", "copywriting", "貼文最希望讓讀者記住的重點是什麼？", false),
      f("conversionGoal", "轉換目標", "copywriting", "是否希望引導購買、預約或追蹤？", false),
      f("brandStory", "品牌故事", "copywriting", "是否需要加入品牌故事或品牌理念？", false),
      f("productSellingPoints", "產品特色", "copywriting", "產品的特色、優勢或賣點有哪些？", false),
      f("restrictedContent", "限制資訊", "copywriting", "是否有不能提及或需要避免的內容？", false),
      f("copyLength", "文案長度", "copywriting", "希望文案是短文案還是完整敘述？", false),
      f("copyStructure", "貼文結構", "copywriting", "是否需要標題、內文與結尾呼籲？", false),
      f("sloganNeed", "標語需求", "copywriting", "是否需要設計 Slogan 或標題句？", false),
      f("hashtagNeed", "Hashtag需求", "copywriting", "是否需要規劃 Hashtag？", false),
      f("platformStyleDiff", "平台風格差異", "copywriting", "不同平台是否需要不同文案風格？", false),
      f("cta", "行動呼籲", "copywriting", "是否需要加入 Call to Action，例如立即購買、立即預約？", false),
      f("trafficLink", "導流連結", "copywriting", "是否需要導流到網站、LINE 或活動頁？", false),
    ],
  },
  [DesignTaskType.banner]: {
    taskType: DesignTaskType.banner,
    displayName: "Banner設計",
    description: "收集 Banner 用途、平台、內容、風格、尺寸與交付需求。",
    keywords: ["banner", "橫幅", "網站banner", "廣告banner", "電商banner"],
    starters: ["Banner設計", "網站Banner設計"],
    sharedContextKeys: ["brandName", "logoFile", "brandColor", "brandFont"],
    fields: [
      f("brandName", "品牌名稱", "basic", "品牌或公司名稱是什麼？"),
      f("bannerPurpose", "Banner用途", "basic", "Banner 主要用途是什麼？例如網站首頁、活動宣傳、電商促銷。"),
      f("usagePlatform", "使用平台", "basic", "Banner 會使用在哪裡？例如網站、電商平台、社群平台或廣告投放。"),
      f("targetAudience", "目標客群", "basic", "Banner 主要想吸引的客戶族群是誰？"),
      f("mainGoal", "主要目的", "basic", "Banner 希望達到的目的是什麼？例如曝光、點擊、購買或活動宣傳。"),
      f("headline", "主標題", "content", "Banner 主要標題文字是什麼？"),
      f("subHeadline", "副標題", "content", "是否需要補充說明文字？", false),
      f("eventInfo", "活動資訊", "content", "是否有活動日期、優惠或促銷內容？", false),
      f("productInfo", "產品資訊", "content", "是否需要介紹產品或服務？", false),
      f("cta", "行動呼籲", "content", "是否需要 Call to Action？例如立即購買、立即預約。", false),
      f("logoFile", "Logo檔案", "assets", "品牌 Logo 是否提供？", false),
      f("productImages", "產品圖片", "assets", "是否提供產品照片或素材？", false),
      f("brandAssets", "品牌素材", "assets", "是否有品牌圖形元素或圖示？", false),
      f("imageStyle", "圖片風格", "assets", "照片或素材是否有統一視覺風格？", false),
      f("stylePreference", "設計風格", "style", "希望 Banner 呈現什麼風格？例如簡約、科技感、活潑、高端。"),
      f("brandColor", "品牌顏色", "style", "是否有指定品牌顏色？", false),
      f("brandFont", "品牌字體", "style", "是否有指定品牌字體？", false),
      f("referenceCases", "參考案例", "style", "是否有喜歡或不喜歡的 Banner 設計？", false),
      f("bannerSize", "Banner尺寸", "layout", "Banner 尺寸是什麼？例如網站 Banner 或廣告尺寸。"),
      f("orientation", "版型方向", "layout", "橫式、直式還是正方形？"),
      f("multiSizeNeed", "是否需要多尺寸", "layout", "是否需要不同尺寸版本？", false),
      f("useDate", "使用時間", "delivery", "Banner 預計何時需要使用？", false),
      f("deadline", "交稿期限", "delivery", "設計需要完成的時間是什麼時候？", false),
      f("fileFormat", "檔案格式", "delivery", "需要可編輯檔或圖片檔嗎？", false),
      f("sizeExtension", "是否需要尺寸延伸", "delivery", "是否需要後續尺寸調整版本？", false),
      f("bannerCopywriting", "Banner文案撰寫", "copywriting", "是否需要協助撰寫主副標文案與內容規劃？", false),
    ],
  },
  [DesignTaskType.edm]: {
    taskType: DesignTaskType.edm,
    displayName: "EDM設計",
    description: "收集 EDM 用途、寄送對象、內容、風格、版型與技術需求。",
    keywords: ["edm", "電子報", "email行銷", "電子郵件設計"],
    starters: ["EDM設計", "電子報設計"],
    sharedContextKeys: ["brandName", "logoFile", "brandColor", "brandFont"],
    fields: [
      f("brandName", "品牌名稱", "basic", "品牌或公司名稱是什麼？"),
      f("edmPurpose", "EDM用途", "basic", "EDM 主要用途是什麼？例如活動宣傳、產品促銷、會員通知。"),
      f("recipients", "寄送對象", "basic", "EDM 主要寄送的客群是誰？例如會員、潛在客戶、VIP 客戶。"),
      f("sendingPlatform", "寄送平台", "basic", "EDM 會透過哪個系統寄送？例如 Mailchimp、電子報系統或公司內部系統。"),
      f("sendingTime", "寄送時間", "basic", "EDM 預計發送的日期或活動期間是什麼時候？"),
      f("headline", "主標題", "content", "EDM 最重要的標題文字是什麼？"),
      f("subHeadline", "副標題", "content", "是否需要補充說明文字？", false),
      f("mainContent", "主要內容", "content", "需要放在 EDM 中的主要文字內容有哪些？"),
      f("productInfo", "產品或服務資訊", "content", "需要介紹哪些產品或服務？", false),
      f("eventInfo", "活動資訊", "content", "是否有活動日期、優惠內容或促銷資訊？", false),
      f("cta", "行動呼籲", "content", "是否需要 Call to Action？例如立即購買、立即報名。", false),
      f("trafficLink", "導流連結", "content", "是否需要導流至網站、活動頁或產品頁？", false),
      f("logoFile", "Logo檔案", "assets", "品牌 Logo 是否提供？", false),
      f("productImages", "產品圖片", "assets", "是否提供產品照片或素材？", false),
      f("brandAssets", "品牌素材", "assets", "是否有品牌圖形元素或設計素材？", false),
      f("imageStyle", "圖片風格", "assets", "是否有指定視覺風格或品牌風格？", false),
      f("stylePreference", "設計風格", "style", "希望 EDM 呈現什麼風格？例如簡約、活潑、科技感、高端。"),
      f("brandColor", "品牌顏色", "style", "是否有指定品牌顏色？", false),
      f("brandFont", "品牌字體", "style", "是否有指定品牌字體？", false),
      f("referenceCases", "參考案例", "style", "是否有喜歡或不喜歡的 EDM 設計？", false),
      f("layoutLength", "版面長度", "layout", "EDM 是否有長度限制？", false),
      f("layoutStructure", "版型結構", "layout", "是否需要分段內容？例如主視覺、產品介紹、活動資訊。", false),
      f("multiBlockDesign", "是否需要多區塊設計", "layout", "例如多產品展示或多活動資訊。", false),
      f("mobileOptimization", "是否需要手機版優化", "layout", "EDM 是否需要特別考慮手機閱讀？", false),
      f("edmFormat", "EDM格式", "technical", "EDM 檔案格式為 JPEG。"),
      f("platformLimitation", "寄送系統限制", "technical", "寄送平台是否有尺寸或檔案限制？", false),
      f("testingNeed", "是否需要測試", "technical", "是否需要測試寄送顯示效果？", false),
      f("trackingNeed", "是否需要連結追蹤", "technical", "是否需要點擊追蹤或分析？", false),
      f("useDate", "使用時間", "delivery", "EDM 預計發送時間是什麼時候？", false),
      f("deadline", "交稿期限", "delivery", "設計需要完成的時間是什麼時候？", false),
      f("fileFormat", "檔案需求", "delivery", "需要可編輯檔或圖片檔嗎？", false),
      f("sendingHelp", "是否需要代發", "delivery", "是否需要協助寄送 EDM？", false),
      f("edmCopywriting", "EDM文案撰寫", "copywriting", "是否需要協助撰寫主副標文案及內容規劃？", false),
    ],
  },
  [DesignTaskType.brand_website]: {
    taskType: DesignTaskType.brand_website,
    displayName: "品牌官網設計",
    description: "收集品牌官網基本資訊、架構規劃、各頁內容、素材、功能與交付需求。",
    keywords: ["網站", "官網", "品牌官網", "網站設計", "企業網站", "brand website"],
    starters: ["品牌官網設計", "公司官網設計"],
    sharedContextKeys: ["brandName", "logoFile", "brandColor", "brandFont", "industry"],
    fields: [
      f("brandName", "品牌名稱", "basic", "公司或品牌名稱是什麼？"),
      f("websitePurpose", "網站目的", "basic", "網站主要用途是什麼？例如品牌形象、產品介紹、電商銷售。"),
      f("targetAudience", "目標客群", "basic", "網站主要面向的客戶族群是誰？"),
      f("websiteLanguage", "網站語言", "basic", "網站需要使用的語言是什麼？例如中文、英文或多語系。"),
      f("websiteStyle", "網站風格", "basic", "希望呈現的網站風格是什麼？例如簡約、科技、高端、自然。"),
      f("websitePages", "網站頁面", "structure", "需要的主要頁面有哪些？例如首頁、品牌介紹、產品頁、聯絡我們。"),
      f("websiteNavigation", "網站導覽", "structure", "網站主選單需要有哪些分類？"),
      f("websiteHierarchy", "網站層級", "structure", "各頁面之間的層級與結構是什麼？"),
      f("ecommerceNeed", "是否需要電商", "structure", "網站是否需要購物功能？", false),
      f("memberSystemNeed", "是否需要會員系統", "structure", "是否需要會員登入或會員功能？", false),
      f("homeBanner", "主視覺Banner", "homepage", "首頁主要視覺圖片或影片是什麼？"),
      f("homeHeadline", "主標題", "homepage", "首頁最重要的品牌標語或主標是什麼？"),
      f("homeBrandIntro", "品牌介紹區塊", "homepage", "品牌或公司簡短介紹內容是什麼？"),
      f("homeProducts", "主打產品區塊", "homepage", "品牌主推產品或服務有哪些？"),
      f("homeFeatures", "品牌特色區塊", "homepage", "品牌優勢或特色說明有哪些？"),
      f("homeNews", "最新消息區塊", "homepage", "是否需要活動、公告或新聞區塊？", false),
      f("homeSocialLinks", "社群連結", "homepage", "品牌社群平台連結有哪些？", false),
      f("homeCTA", "行動呼籲", "homepage", "是否需要按鈕？例如立即購買、了解更多。", false),
      f("aboutBrandStory", "品牌故事", "about", "品牌成立背景與理念是什麼？", false),
      f("aboutBrandValues", "品牌理念", "about", "品牌核心價值與使命是什麼？", false),
      f("aboutBrandFeatures", "品牌特色", "about", "品牌與競爭品牌的差異是什麼？", false),
      f("aboutBrandHistory", "品牌歷程", "about", "品牌發展時間軸或重要里程碑有哪些？", false),
      f("aboutTeam", "團隊介紹", "about", "是否需要公司團隊或創辦人介紹？", false),
      f("aboutPhotos", "品牌照片", "about", "是否有品牌形象或公司照片？", false),
      f("productCategories", "產品分類", "product", "產品主要分類有哪些？例如保養品、食品、配件。", false),
      f("categoryIntro", "分類介紹", "product", "每個分類是否需要簡短介紹？", false),
      f("productList", "產品列表", "product", "每個分類下的產品列表有哪些？", false),
      f("productThumbnails", "產品縮圖", "product", "是否有產品展示圖片？", false),
      f("productPricing", "產品價格", "product", "是否需要顯示價格？", false),
      f("filterFunction", "篩選功能", "product", "是否需要分類或條件篩選？", false),
      f("productDetailName", "產品名稱", "productDetail", "產品完整名稱是什麼？", false),
      f("productDetailImages", "產品圖片", "productDetail", "是否有產品展示圖片或情境圖？", false),
      f("productDetailIntro", "產品介紹", "productDetail", "產品特色與賣點是什麼？", false),
      f("productDetailSpecs", "產品規格", "productDetail", "產品容量、尺寸或規格是什麼？", false),
      f("productDetailPrice", "產品價格", "productDetail", "產品售價是多少？", false),
      f("productDetailPurchase", "購買方式", "productDetail", "是否需要加入購物車或購買連結？", false),
      f("productDetailUsage", "產品說明", "productDetail", "是否需要使用方法或產品說明？", false),
      f("productDetailIngredients", "產品成分", "productDetail", "若為食品或保養品，是否需要標示成分？", false),
      f("productDetailReviews", "產品評價", "productDetail", "是否需要顧客評價區？", false),
      f("newsEvents", "活動資訊", "news", "是否需要品牌活動或促銷資訊？", false),
      f("newsAnnouncements", "品牌公告", "news", "是否需要公司公告或重要訊息？", false),
      f("newsArticles", "文章內容", "news", "是否需要活動或文章內容？", false),
      f("newsImages", "活動圖片", "news", "是否有活動或文章相關圖片？", false),
      f("contactForm", "聯絡表單", "contact", "是否需要填寫聯絡表單？", false),
      f("contactPhone", "公司電話", "contact", "聯絡電話是什麼？", false),
      f("contactEmail", "Email", "contact", "聯絡信箱是什麼？", false),
      f("contactAddress", "公司地址", "contact", "公司或門市地址是什麼？", false),
      f("contactMap", "Google地圖", "contact", "是否需要嵌入地圖？", false),
      f("contactSocialLinks", "社群連結", "contact", "品牌社群平台連結有哪些？", false),
      f("logoFile", "Logo檔案", "assets", "品牌 Logo 是否提供？", false),
      f("brandColor", "品牌顏色", "assets", "品牌主色與輔助色是什麼？", false),
      f("brandFont", "品牌字體", "assets", "是否有品牌指定字體？", false),
      f("imageAssets", "圖片素材", "assets", "是否有產品照片或品牌照片？", false),
      f("videoAssets", "影片素材", "assets", "是否有品牌影片？", false),
      f("shoppingFunction", "購物功能", "function", "是否需要電商購物系統？", false),
      f("memberFunction", "會員功能", "function", "是否需要會員登入或會員中心？", false),
      f("searchFunction", "搜尋功能", "function", "是否需要網站搜尋？", false),
      f("subscribeFunction", "訂閱功能", "function", "是否需要電子報訂閱？", false),
      f("socialIntegration", "社群串接", "function", "是否需要串接社群平台？", false),
      f("launchDate", "網站上線時間", "delivery", "預計網站上線日期是什麼時候？", false),
      f("designDeadline", "設計完成期限", "delivery", "網站設計完成時間是什麼時候？", false),
      f("backendManagement", "後台管理", "delivery", "是否需要網站後台管理功能？", false),
      f("maintenance", "網站維護", "delivery", "是否需要後續維護服務？", false),
      f("rwdDesign", "手機與電腦版RWD", "delivery", "是否需要手機與電腦版 RWD 製作？"),
      f("websiteCopywriting", "網站內容規劃", "copywriting", "是否需要協助撰寫畫面文案及產品內容？", false),
    ],
  },
  [DesignTaskType.landing_page]: {
    taskType: DesignTaskType.landing_page,
    displayName: "一頁式網站",
    description: "收集一頁式網站目標、頁面架構、各區塊內容、素材與交付需求。",
    keywords: ["一頁式", "landing page", "一頁式網站", "銷售頁"],
    starters: ["一頁式網站設計", "Landing Page 設計"],
    sharedContextKeys: ["brandName", "logoFile", "brandColor", "brandFont"],
    fields: [
      f("brandName", "品牌名稱", "basic", "公司或品牌名稱是什麼？"),
      f("productOrServiceName", "產品或服務名稱", "basic", "此一頁式網站主要介紹的產品或服務是什麼？"),
      f("pagePurpose", "頁面目的", "basic", "網站主要目標是什麼？例如產品銷售、活動報名、蒐集名單、品牌介紹。"),
      f("targetAudience", "目標客群", "basic", "主要希望吸引的客戶族群是誰？"),
      f("trafficSource", "導流來源", "basic", "流量來源是什麼？例如廣告投放、社群導流、EDM 或搜尋。"),
      f("pageSections", "頁面區塊", "structure", "一頁式網站需要包含哪些區塊？例如主視覺、產品介紹、特色、價格。"),
      f("readingOrder", "閱讀順序", "structure", "希望使用者閱讀內容的順序是什麼？"),
      f("mainConversion", "主要轉換行為", "structure", "頁面最重要的行動是什麼？例如購買、填表單、預約、加入 LINE。"),
      f("ctaButtons", "行動按鈕", "structure", "需要設置哪些 Call to Action？例如立即購買、立即報名、了解更多。"),
      f("heroHeadline", "主標題", "hero", "頁面最重要的主標題或核心訊息是什麼？"),
      f("heroSubHeadline", "副標題", "hero", "補充說明產品或服務的文字是什麼？"),
      f("heroImage", "主視覺圖片", "hero", "是否有產品圖片或品牌形象圖片？", false),
      f("heroCTA", "行動按鈕", "hero", "是否需要在主視覺區放立即購買或了解更多按鈕？", false),
      f("productIntro", "產品介紹", "product", "產品或服務的基本說明是什麼？"),
      f("sellingPoints", "主要賣點", "product", "產品或服務最重要的特色有哪些？"),
      f("featureDescription", "功能說明", "product", "產品功能或服務內容有哪些？", false),
      f("usageScenario", "使用情境", "product", "產品適合的使用情境或族群是什麼？", false),
      f("productSpecs", "產品規格", "productInfo", "產品容量、尺寸或規格是什麼？", false),
      f("productContent", "產品內容", "productInfo", "產品內容物或服務項目有哪些？", false),
      f("productImages", "產品圖片", "productInfo", "是否有產品展示圖片或情境圖？", false),
      f("productPrice", "產品價格", "productInfo", "產品售價或方案價格是多少？", false),
      f("customerReviews", "客戶評價", "trust", "是否有顧客評論或使用心得？", false),
      f("caseStudies", "案例或成果", "trust", "是否有成功案例或成果展示？", false),
      f("mediaOrPartners", "媒體或合作品牌", "trust", "是否有媒體報導或合作品牌？", false),
      f("certifications", "認證標章", "trust", "是否有產品認證或專利標誌？", false),
      f("pricingPlans", "價格方案", "promotion", "是否有不同價格方案？", false),
      f("promotions", "優惠活動", "promotion", "是否有折扣或促銷？", false),
      f("activityDeadline", "活動期限", "promotion", "是否有活動時間或倒數？", false),
      f("bundleOffers", "套餐或組合", "promotion", "是否有組合商品或方案？", false),
      f("faqQuestions", "常見問題", "faq", "客戶常見疑問有哪些？", false),
      f("faqAnswers", "解答內容", "faq", "問題的說明與解答是什麼？", false),
      f("registrationForm", "報名表單", "conversion", "是否需要填寫表單蒐集資料？", false),
      f("purchaseButton", "購買按鈕", "conversion", "是否需要購買連結？", false),
      f("contactMethod", "聯絡方式", "conversion", "電話、LINE 或客服方式是什麼？", false),
      f("qrCode", "QR Code", "conversion", "是否需要導流至 LINE 或其他平台？", false),
      f("logoFile", "Logo檔案", "assets", "品牌 Logo 是否提供？", false),
      f("brandColor", "品牌顏色", "assets", "品牌主色與輔助色是什麼？", false),
      f("brandFont", "品牌字體", "assets", "是否有指定品牌字體？", false),
      f("imageAssets", "圖片素材", "assets", "是否有產品照片或品牌照片？", false),
      f("videoAssets", "影片素材", "assets", "是否有品牌影片或產品影片？", false),
      f("referenceWebsite", "參考網站", "assets", "是否有喜歡或不喜歡的一頁式網站案例？", false),
      f("rwdNeed", "是否需要RWD", "technical", "是否需要手機與電腦版適配？"),
      f("launchDate", "上線時間", "delivery", "網站預計上線日期是什麼時候？", false),
      f("designDeadline", "設計完成期限", "delivery", "設計需要完成的時間是什麼時候？", false),
      f("publishPlatform", "發佈平台", "delivery", "發佈平台為何？需交付什麼檔案？", false),
    ],
  },
  [DesignTaskType.ecommerce_website]: {
    taskType: DesignTaskType.ecommerce_website,
    displayName: "電商網站設計（套版）",
    description: "收集電商套版網站基本資訊、首頁區塊、分頁內容、素材、功能與交付需求。",
    keywords: ["電商網站", "套版網站", "電商設計", "shopline", "91app", "wix"],
    starters: ["電商網站設計", "套版網站設計"],
    sharedContextKeys: ["brandName", "logoFile", "brandColor", "brandFont"],
    fields: [
      f("brandName", "品牌名稱", "basic", "公司或品牌名稱是什麼？"),
      f("websitePurpose", "網站用途", "basic", "網站主要目的是什麼？例如品牌介紹、產品展示、企業形象。"),
      f("targetAudience", "目標客群", "basic", "網站主要面向的客戶族群是誰？"),
      f("websiteLanguage", "網站語言", "basic", "網站使用語言是什麼？例如中文、英文或多語系。"),
      f("referenceWebsite", "參考網站", "basic", "是否有喜歡或不喜歡的網站風格？", false),
      f("homeBanner", "首頁Banner", "homepage", "首頁是否需要主視覺 Banner 或輪播 Banner？"),
      f("bannerHeadline", "Banner主標題", "homepage", "每個 Banner 需要呈現的標題文字是什麼？"),
      f("bannerSubHeadline", "Banner副標題", "homepage", "是否需要補充說明文字？", false),
      f("bannerImages", "Banner圖片", "homepage", "是否提供 Banner 圖片或產品圖片？", false),
      f("bannerLinks", "Banner連結", "homepage", "Banner 是否需要連結到指定頁面？", false),
      f("featuredProducts", "主打產品或服務", "homepage", "首頁是否需要展示主打產品或服務？", false),
      f("brandIntro", "品牌簡介", "homepage", "是否需要簡短品牌介紹？", false),
      f("categoryEntrance", "產品分類入口", "homepage", "是否需要放產品分類入口？", false),
      f("homeEventInfo", "活動資訊", "homepage", "是否需要展示活動或優惠資訊？", false),
      f("homeSocialLinks", "社群導流", "homepage", "是否需要放社群平台連結或貼文？", false),
      f("aboutPage", "品牌介紹頁", "pages", "是否需要品牌故事、品牌理念、公司介紹等內容？", false),
      f("productPage", "產品或服務頁", "pages", "是否需要產品或服務介紹？", false),
      f("productCategoryPage", "產品分類頁", "pages", "產品是否需要分類展示？", false),
      f("portfolioPage", "案例或作品頁", "pages", "是否需要展示案例或作品？", false),
      f("newsPage", "最新消息頁", "pages", "是否需要放活動、公告或文章？", false),
      f("faqPage", "常見問題頁", "pages", "是否需要 FAQ 內容？", false),
      f("contactPage", "聯絡我們頁", "pages", "是否需要聯絡資訊或表單？", false),
      f("pageTitle", "頁面標題", "pageContent", "每個分頁的標題文字是什麼？", false),
      f("pageContentText", "頁面內容文字", "pageContent", "分頁需要呈現的介紹文字有哪些？", false),
      f("pageImages", "圖片素材", "pageContent", "是否提供產品圖片或品牌圖片？", false),
      f("pageVideos", "影片素材", "pageContent", "是否需要放影片內容？", false),
      f("pageDownloads", "下載資料", "pageContent", "是否需要放文件或型錄下載？", false),
      f("logoFile", "Logo檔案", "assets", "品牌 Logo 是否提供？", false),
      f("brandColor", "品牌顏色", "assets", "品牌主色與輔助色是什麼？", false),
      f("brandFont", "品牌字體", "assets", "是否有指定品牌字體？", false),
      f("imageAssets", "圖片素材", "assets", "是否有產品照片或品牌照片？", false),
      f("videoAssets", "影片素材", "assets", "是否有品牌或產品影片？", false),
      f("contactForm", "聯絡表單", "function", "是否需要填寫聯絡表單？", false),
      f("googleMap", "Google地圖", "function", "是否需要嵌入地圖？", false),
      f("socialLinks", "社群連結", "function", "是否需要連結社群平台？", false),
      f("externalLinks", "外部連結", "function", "是否需要連結外部網站或購物平台？", false),
      f("launchDate", "網站上線時間", "delivery", "預計網站上線日期是什麼時候？", false),
      f("designDeadline", "設計完成期限", "delivery", "設計需要完成的時間是什麼時候？", false),
      f("uploadHelp", "是否需要幫客戶上傳", "delivery", "提供圖檔讓客戶自己上架，還是幫客戶上傳？", false),
    ],
  },
  [DesignTaskType.event_backdrop]: {
    taskType: DesignTaskType.event_backdrop,
    displayName: "活動背板設計",
    description: "收集活動背板基本資訊、用途情境、內容、風格、尺寸與輸出製作需求。",
    keywords: ["背板", "活動背板", "舞台背板", "記者會背板", "拍照背板"],
    starters: ["活動背板設計", "背板設計"],
    sharedContextKeys: ["brandName", "logoFile", "brandColor"],
    fields: [
      f("eventName", "活動名稱", "basic", "活動名稱或活動主題是什麼？"),
      f("eventDate", "活動日期", "basic", "活動舉辦日期是什麼時候？"),
      f("eventLocation", "活動地點", "basic", "活動舉辦場地名稱是什麼？"),
      f("eventType", "活動性質", "basic", "活動性質是什麼？例如品牌活動、記者會、開幕、展覽、論壇。"),
      f("organizer", "主辦單位", "basic", "主辦公司或品牌名稱是什麼？"),
      f("usageScenario", "使用情境", "usage", "背板用途是什麼？例如拍照區、舞台背景、記者會背景。"),
      f("viewingDistance", "觀看距離", "usage", "背板主要觀看距離是什麼？例如拍照近距離或舞台遠距離。"),
      f("photoAreaNeed", "是否需要拍照區", "usage", "背板是否主要作為拍照打卡使用？", false),
      f("standingSpaceNeed", "是否需要留人物空間", "usage", "是否需要預留站立拍照的位置？", false),
      f("lightingNeed", "背板是否有打燈", "usage", "背板是否有打燈？", false),
      f("headline", "主標題", "content", "背板最主要的標題文字是什麼？"),
      f("subHeadline", "副標題", "content", "是否需要補充說明文字？", false),
      f("eventInfoContent", "活動資訊", "content", "是否需要放活動日期或活動名稱？", false),
      f("logoDisplay", "Logo展示", "content", "是否需要放品牌或合作單位 Logo 或贊助商 Logo？", false),
      f("slogan", "標語或Slogan", "content", "是否需要品牌或活動標語？", false),
      f("logoFile", "Logo檔案", "assets", "品牌或合作單位 Logo 是否提供？", false),
      f("imageAssets", "圖片素材", "assets", "是否需要放產品圖片或活動圖片？", false),
      f("brandAssets", "品牌素材", "assets", "是否有品牌圖形或設計元素？", false),
      f("backgroundAssets", "背景素材", "assets", "是否有指定背景圖片或主視覺？", false),
      f("stylePreference", "設計風格", "style", "希望背板呈現什麼風格？例如簡約、科技感、正式、活潑。"),
      f("brandColor", "品牌顏色", "style", "是否有指定品牌顏色？", false),
      f("referenceCases", "參考案例", "style", "是否有喜歡或不喜歡的背板設計？", false),
      f("brandVisual", "品牌視覺", "style", "是否需要符合品牌視覺系統？", false),
      f("backdropSize", "背板尺寸", "layout", "背板實際尺寸是多少？例如寬度與高度。"),
      f("structureLimit", "是否有結構限制", "layout", "背板是否有框架或支架限制？", false),
      f("outputMaterial", "輸出材質", "output", "輸出材質是什麼？例如帆布、背板布、KT板、PVC板。", false),
      f("lightingEffect", "是否需要燈光", "output", "背板是否會搭配燈光效果？", false),
      f("threeDText", "是否需要立體字", "output", "是否需要立體字或立體 Logo？", false),
      f("breakFrameDesign", "是否需要破框設計", "output", "是否需要立體或破框效果？", false),
      f("eventTime", "活動時間", "delivery", "背板需要使用的日期是什麼時候？"),
      f("deadline", "交稿期限", "delivery", "設計完成的時間是什麼時候？", false),
      f("outputHelp", "是否需要協助輸出", "delivery", "是否需要協助製作與輸出？", false),
      f("installationHelp", "是否需要現場安裝", "delivery", "是否需要協助安裝背板？", false),
      f("backdropCopywriting", "活動背板內容規劃", "copywriting", "是否需要協助撰寫畫面文案？", false),
    ],
  },
  [DesignTaskType.x_banner]: {
    taskType: DesignTaskType.x_banner,
    displayName: "X展架設計",
    description: "收集 X 展架基本資訊、主視覺延伸、用途、內容、風格、尺寸與輸出需求。",
    keywords: ["x展架", "展架", "x banner", "易拉寶", "roll up"],
    starters: ["X展架設計", "展架設計"],
    sharedContextKeys: ["brandName", "logoFile", "brandColor"],
    fields: [
      f("eventName", "活動名稱", "basic", "活動名稱或活動主題是什麼？"),
      f("eventDate", "活動日期", "basic", "活動舉辦日期是什麼時候？", false),
      f("eventLocation", "活動地點", "basic", "活動舉辦場地名稱是什麼？", false),
      f("usageScenario", "使用情境", "basic", "使用情境是什麼？例如展覽、門市宣傳、活動入口、產品介紹。"),
      f("organizer", "主辦單位", "basic", "主辦公司或品牌名稱是什麼？"),
      f("hasKeyVisual", "是否已有主視覺", "keyVisual", "是否已有活動或品牌主視覺設計？", false),
      f("keyVisualExtension", "主視覺延伸使用", "keyVisual", "X 展架是否需要延伸主視覺設計？", false),
      f("keyVisualFile", "主視覺檔案", "keyVisual", "是否提供主視覺原始設計檔或圖片素材？", false),
      f("mainPurpose", "主要目的", "usage", "展架主要用途是什麼？例如品牌曝光、產品介紹、活動宣傳。"),
      f("placementLocation", "擺放位置", "usage", "展架擺放位置在哪裡？例如入口、舞台旁、攤位旁、門市。"),
      f("trafficNeed", "是否需要導流", "usage", "是否需要導流至網站、LINE 或活動頁？", false),
      f("headline", "主標題", "content", "展架最主要的標題文字是什麼？"),
      f("subHeadline", "副標題", "content", "補充說明的文字內容是什麼？", false),
      f("eventOrProductInfo", "活動或產品資訊", "content", "需要呈現的活動或產品內容有哪些？", false),
      f("brandLogo", "品牌Logo", "content", "是否需要放品牌 Logo？", false),
      f("slogan", "標語或Slogan", "content", "是否需要品牌標語？", false),
      f("qrCode", "QR Code", "content", "是否需要放網站、LINE 或活動報名 QR Code？", false),
      f("contactInfo", "聯絡方式", "content", "是否需要放電話、網站或社群資訊？", false),
      f("logoFile", "Logo檔案", "assets", "品牌 Logo 是否提供？", false),
      f("imageAssets", "圖片素材", "assets", "是否有產品照片或品牌形象圖片？", false),
      f("brandGraphics", "品牌圖形", "assets", "是否有品牌圖騰或設計元素？", false),
      f("qrCodeFile", "QR Code圖檔", "assets", "若需要導流，是否提供 QR Code？", false),
      f("stylePreference", "設計風格", "style", "希望展架呈現什麼風格？例如簡約、科技感、活潑、專業。"),
      f("brandColor", "品牌顏色", "style", "是否有指定品牌顏色？", false),
      f("referenceCases", "參考案例", "style", "是否有喜歡或不喜歡的展架設計？", false),
      f("brandVisual", "品牌視覺", "style", "是否需要符合品牌視覺系統？", false),
      f("bannerSize", "展架尺寸", "layout", "展架尺寸是什麼？例如 60×160cm、80×180cm。"),
      f("outputMaterial", "輸出材質", "output", "輸出材質是亮面還是霧面？", false),
      f("outputHelp", "是否需要協助輸出", "output", "是否需要協助印刷與輸出？", false),
      f("useDate", "使用日期", "delivery", "展架需要使用的時間是什麼時候？", false),
      f("deadline", "交稿期限", "delivery", "設計完成時間是什麼時候？", false),
      f("shippingNeed", "是否需要寄送", "delivery", "是否需要寄送至活動地點？", false),
    ],
  },
  [DesignTaskType.standing_sign]: {
    taskType: DesignTaskType.standing_sign,
    displayName: "立牌設計",
    description: "收集立牌基本資訊、主視覺延伸、內容、形式、尺寸與輸出製作需求。",
    keywords: ["立牌", "人形立牌", "迎賓立牌", "standing sign"],
    starters: ["立牌設計"],
    sharedContextKeys: ["brandName", "logoFile", "brandColor"],
    fields: [
      f("eventName", "活動名稱", "basic", "活動名稱或活動主題是什麼？"),
      f("eventDate", "活動日期", "basic", "活動舉辦日期是什麼時候？", false),
      f("eventLocation", "活動地點", "basic", "活動舉辦場地名稱是什麼？", false),
      f("usageScenario", "使用情境", "basic", "使用情境是什麼？例如門市展示、活動迎賓、拍照打卡、產品介紹。"),
      f("organizer", "主辦單位", "basic", "主辦公司或品牌名稱是什麼？"),
      f("hasKeyVisual", "是否已有主視覺", "keyVisual", "是否已有活動或品牌主視覺設計？", false),
      f("keyVisualExtension", "主視覺延伸使用", "keyVisual", "立牌是否需要延伸主視覺設計？", false),
      f("keyVisualFile", "主視覺檔案", "keyVisual", "是否提供主視覺原始設計檔或圖片素材？", false),
      f("keyVisualElements", "主視覺元素", "keyVisual", "是否需要沿用主視覺中的圖形、背景或裝飾元素？", false),
      f("headline", "主標題", "content", "立牌主要標題文字是什麼？"),
      f("subHeadline", "副標題", "content", "補充說明的文字內容是什麼？", false),
      f("productOrEventInfo", "產品或活動資訊", "content", "需要呈現的產品或活動內容有哪些？", false),
      f("brandLogo", "品牌Logo", "content", "是否需要放品牌 Logo？", false),
      f("slogan", "標語或Slogan", "content", "是否需要品牌或活動標語？", false),
      f("qrCode", "QR Code", "content", "是否需要放網站、LINE 或活動報名 QR Code？", false),
      f("contactInfo", "聯絡方式", "content", "是否需要放電話、網站或社群資訊？", false),
      f("signType", "立牌類型", "form", "立牌類型是什麼？例如人物立牌、迎賓立牌、產品介紹立牌。"),
      f("signShape", "立牌形狀", "form", "立牌形狀是什麼？例如長方形、人物造型或客製造型。"),
      f("signOrientation", "立牌方向", "form", "直式還是橫式？", false),
      f("dieCutNeed", "是否需要造型裁切", "form", "是否需要依圖形輪廓裁切？", false),
      f("doubleSidedPrint", "是否需要背面印刷", "form", "是否需要雙面內容？", false),
      f("logoFile", "Logo檔案", "assets", "品牌 Logo 是否提供？", false),
      f("imageAssets", "圖片素材", "assets", "是否有產品照片或人物照片？", false),
      f("brandGraphics", "品牌圖形", "assets", "是否有品牌圖騰或設計元素？", false),
      f("qrCodeFile", "QR Code圖檔", "assets", "若需要導流，是否提供 QR Code？", false),
      f("signSize", "立牌尺寸", "layout", "立牌實際尺寸是多少？例如高 180cm 或其他客製尺寸。"),
      f("baseType", "底座形式", "layout", "底座形式是什麼？例如腳架式、鐵架或背架支撐。", false),
      f("safeArea", "安全範圍", "layout", "是否需要預留裁切安全距離？", false),
      f("bleedNeed", "出血需求", "layout", "輸出是否需要出血？", false),
      f("outputMaterial", "輸出材質", "output", "輸出材質是什麼？例如 KT 板、PVC 板、雪弗板或壓克力。", false),
      f("laminationNeed", "是否需要上膜", "output", "是否需要亮膜或霧膜？", false),
      f("standNeed", "是否需要支架", "output", "是否需要搭配立牌支架？", false),
      f("outputHelp", "是否需要協助輸出", "output", "是否需要協助印刷與製作？", false),
      f("useDate", "使用日期", "delivery", "立牌需要使用的時間是什麼時候？", false),
      f("deadline", "交稿期限", "delivery", "設計完成時間是什麼時候？", false),
      f("shippingNeed", "是否需要寄送", "delivery", "是否需要寄送至活動地點？", false),
      f("urgentNeed", "是否需要急件", "delivery", "是否為急件製作？", false),
    ],
  },
  [DesignTaskType.hand_held_sign]: {
    taskType: DesignTaskType.hand_held_sign,
    displayName: "手拿牌設計",
    description: "收集手拿牌基本資訊、主視覺延伸、內容、款式、風格、尺寸與輸出需求。",
    keywords: ["手拿牌", "拍照道具", "打卡牌", "hand held sign"],
    starters: ["手拿牌設計"],
    sharedContextKeys: ["brandName", "logoFile", "brandColor"],
    fields: [
      f("eventName", "活動名稱", "basic", "活動名稱或活動主題是什麼？"),
      f("eventDate", "活動日期", "basic", "活動舉辦日期是什麼時候？", false),
      f("eventLocation", "活動地點", "basic", "活動舉辦場地名稱是什麼？", false),
      f("usageScenario", "使用情境", "basic", "使用情境是什麼？例如活動拍照、宣傳活動、記者會、展覽打卡。"),
      f("organizer", "主辦單位", "basic", "主辦公司或品牌名稱是什麼？"),
      f("hasKeyVisual", "是否已有主視覺", "keyVisual", "是否已有活動或品牌主視覺設計？", false),
      f("keyVisualExtension", "主視覺延伸使用", "keyVisual", "手拿牌是否需要延伸主視覺設計？", false),
      f("keyVisualFile", "主視覺檔案", "keyVisual", "是否提供主視覺原始設計檔或圖片素材？", false),
      f("keyVisualElements", "主視覺元素", "keyVisual", "是否需要沿用主視覺中的圖形、背景或裝飾元素？", false),
      f("textContent", "文字內容", "content", "手拿牌需要呈現的文字是什麼？"),
      f("slogan", "標語或口號", "content", "是否有活動標語或宣傳口號？", false),
      f("brandLogo", "品牌Logo", "content", "是否需要放品牌 Logo？", false),
      f("eventHashtag", "活動Hashtag", "content", "是否需要放活動 Hashtag 或社群標籤？", false),
      f("socialInfo", "社群資訊", "content", "是否需要放品牌帳號或社群資訊？", false),
      f("qrCode", "QR Code", "content", "是否需要放活動或網站 QR Code？", false),
      f("signVariants", "手拿牌款式", "variants", "需要幾種不同款式的手拿牌？"),
      f("variantTexts", "每款文字", "variants", "每款手拿牌是否有不同文字？", false),
      f("graphicNeed", "是否需要圖案", "variants", "是否需要搭配插圖或圖形？", false),
      f("interactiveTexts", "是否需要人物互動文字", "variants", "例如「我最美」「今天開幕」等拍照文字？", false),
      f("stylePreference", "設計風格", "style", "希望手拿牌呈現什麼風格？例如可愛、活潑、正式、品牌感。"),
      f("brandColor", "品牌顏色", "style", "是否有指定品牌顏色？", false),
      f("referenceCases", "參考案例", "style", "是否有喜歡或不喜歡的手拿牌設計？", false),
      f("brandVisual", "品牌視覺", "style", "是否需要符合品牌視覺系統？", false),
      f("signSize", "手拿牌尺寸", "layout", "手拿牌尺寸是什麼？例如 A3、A4 或客製尺寸。"),
      f("signShape", "形狀形式", "layout", "形狀是什麼？例如圓形、對話框、雲朵、星形或客製造型。"),
      f("handleNeed", "是否需要手柄", "layout", "是否需要加手柄設計？", false),
      f("doubleSidedDesign", "是否需要雙面設計", "layout", "是否需要正反兩面不同內容？", false),
      f("outputMaterial", "輸出材質", "output", "有無指定材質？例如 KT 板、PVC 板、合成板。", false),
      f("dieCutNeed", "是否需要刀模", "output", "是否需要特殊造型裁切？", false),
      f("laminationNeed", "是否需要上膜", "output", "是否需要亮膜或霧膜？", false),
      f("outputHelp", "是否需要協助輸出", "output", "是否需要協助印刷與製作？", false),
      f("useDate", "使用日期", "delivery", "手拿牌需要使用的時間是什麼時候？", false),
      f("deadline", "交稿期限", "delivery", "設計完成時間是什麼時候？", false),
      f("shippingNeed", "是否需要寄送", "delivery", "是否需要寄送至活動地點？", false),
    ],
  },
  [DesignTaskType.banner_cloth]: {
    taskType: DesignTaskType.banner_cloth,
    displayName: "布條設計",
    description: "收集布條基本資訊、主視覺延伸、內容、風格、尺寸與輸出製作需求。",
    keywords: ["布條", "布旗", "活動布條", "宣傳布條"],
    starters: ["布條設計"],
    sharedContextKeys: ["brandName", "logoFile", "brandColor"],
    fields: [
      f("eventName", "活動名稱", "basic", "活動名稱或活動主題是什麼？"),
      f("eventDate", "活動日期", "basic", "活動舉辦日期是什麼時候？", false),
      f("eventLocation", "活動地點", "basic", "活動舉辦場地名稱是什麼？", false),
      f("usageScenario", "使用情境", "basic", "使用情境是什麼？例如活動入口、舞台背景、街道宣傳、門市外牆。"),
      f("organizer", "主辦單位", "basic", "主辦公司或品牌名稱是什麼？"),
      f("hasKeyVisual", "是否已有主視覺", "keyVisual", "是否已有活動或品牌主視覺設計？", false),
      f("keyVisualExtension", "主視覺延伸使用", "keyVisual", "布條是否需要延伸主視覺設計？", false),
      f("keyVisualFile", "主視覺檔案", "keyVisual", "是否提供主視覺原始設計檔或圖片素材？", false),
      f("keyVisualElements", "主視覺元素", "keyVisual", "是否需要沿用主視覺中的圖形、背景或裝飾元素？", false),
      f("headline", "主標題", "content", "布條主要標題文字是什麼？"),
      f("subHeadline", "副標題", "content", "補充說明文字是什麼？", false),
      f("eventInfoContent", "活動資訊", "content", "是否需要放活動日期、時間或地點？", false),
      f("brandLogo", "品牌Logo", "content", "是否需要放品牌 Logo 或主辦單位 Logo？", false),
      f("slogan", "標語或Slogan", "content", "是否需要品牌或活動標語？", false),
      f("contactInfo", "聯絡方式", "content", "是否需要放電話、網站或社群資訊？", false),
      f("stylePreference", "設計風格", "style", "希望布條呈現什麼風格？例如簡約、正式、活動感。"),
      f("brandColor", "品牌顏色", "style", "是否有指定品牌顏色？", false),
      f("referenceCases", "參考案例", "style", "是否有喜歡或不喜歡的布條設計？", false),
      f("brandVisual", "品牌視覺", "style", "是否需要符合品牌視覺系統？", false),
      f("logoFile", "Logo檔案", "assets", "品牌 Logo 或主辦單位 Logo 是否提供？", false),
      f("imageAssets", "圖片素材", "assets", "是否需要放產品圖片或活動圖片？", false),
      f("brandGraphics", "品牌圖形", "assets", "是否有品牌圖騰或設計元素？", false),
      f("clothSize", "布條尺寸", "layout", "布條實際尺寸是多少？例如寬度與高度。"),
      f("clothOrientation", "布條方向", "layout", "橫式還是直式？"),
      f("viewingDistance", "觀看距離", "layout", "主要觀看距離是什麼？例如遠距離閱讀或近距離觀看。", false),
      f("safeArea", "安全範圍", "layout", "是否需要預留裁切安全距離？", false),
      f("bleedNeed", "出血需求", "layout", "輸出是否需要出血？", false),
      f("outputMaterial", "輸出材質", "output", "輸出材質是什麼？例如帆布、布旗或 PVC 布。", false),
      f("grommetNeed", "是否需要打洞", "output", "是否需要四角或邊緣打洞固定？", false),
      f("hemNeed", "是否需要包邊", "output", "是否需要車縫包邊？", false),
      f("ropeNeed", "是否需要繩子", "output", "是否需要附固定繩子？", false),
      f("outputHelp", "是否需要協助輸出", "output", "是否需要協助印刷與製作？", false),
      f("useDate", "使用日期", "delivery", "布條需要使用的時間是什麼時候？", false),
      f("deadline", "交稿期限", "delivery", "設計完成時間是什麼時候？", false),
      f("shippingNeed", "是否需要寄送", "delivery", "是否需要寄送至活動地點？", false),
      f("urgentNeed", "是否需要急件", "delivery", "是否為急件製作？", false),
    ],
  },
  [DesignTaskType.outdoor_signboard]: {
    taskType: DesignTaskType.outdoor_signboard,
    displayName: "戶外看板設計",
    description: "收集戶外看板基本資訊、主視覺延伸、內容、風格、尺寸、安裝環境與輸出需求。",
    keywords: ["戶外看板", "看板", "outdoor signboard", "廣告看板"],
    starters: ["戶外看板設計", "看板設計"],
    sharedContextKeys: ["brandName", "logoFile", "brandColor"],
    fields: [
      f("signboardName", "看板名稱", "basic", "看板用途或宣傳主題是什麼？"),
      f("installLocation", "設置地點", "basic", "看板實際安裝位置在哪裡？例如門市外牆、建築外牆、道路旁、屋頂看板。"),
      f("purpose", "使用目的", "basic", "使用目的是什麼？例如品牌宣傳、產品宣傳、活動宣傳、店面招牌。"),
      f("viewingAudience", "觀看對象", "basic", "主要觀看族群是誰？例如車流、行人或商圈人潮。"),
      f("usageDuration", "使用期限", "basic", "短期活動宣傳還是長期品牌看板？"),
      f("hasKeyVisual", "是否已有主視覺", "keyVisual", "是否已有品牌或活動主視覺設計？", false),
      f("keyVisualExtension", "主視覺延伸使用", "keyVisual", "看板是否需要延伸主視覺畫面？", false),
      f("keyVisualFile", "主視覺檔案", "keyVisual", "是否提供主視覺原始設計檔或圖片素材？", false),
      f("keyVisualElements", "主視覺元素", "keyVisual", "是否需要沿用主視覺中的背景、圖形或裝飾元素？", false),
      f("headline", "主標題", "content", "看板主要宣傳標題是什麼？"),
      f("subHeadline", "副標題", "content", "補充說明或次要文字是什麼？", false),
      f("brandLogo", "品牌Logo", "content", "是否需要放品牌 Logo 或企業標誌？", false),
      f("productInfo", "產品或服務資訊", "content", "是否需要呈現產品名稱或服務內容？", false),
      f("contactInfo", "聯絡資訊", "content", "是否需要放電話、地址、網站或 QR Code？", false),
      f("brandSlogan", "品牌標語", "content", "是否需要加入品牌標語或 Slogan？", false),
      f("stylePreference", "設計風格", "style", "希望看板呈現什麼風格？例如企業感、活動感、簡約或高端。"),
      f("brandColor", "品牌顏色", "style", "是否有指定品牌顏色或品牌色系？", false),
      f("referenceCases", "參考案例", "style", "是否有喜歡或不喜歡的看板設計案例？", false),
      f("brandVisual", "品牌視覺", "style", "是否需要符合品牌識別系統？", false),
      f("logoFile", "Logo檔案", "assets", "品牌 Logo 或企業識別標誌是否提供？", false),
      f("imageAssets", "圖片素材", "assets", "是否需要放產品照片或形象圖片？", false),
      f("brandGraphics", "品牌圖形", "assets", "是否有品牌圖騰或裝飾元素？", false),
      f("textContent", "文字內容", "assets", "所有需要呈現的完整文字資訊有哪些？", false),
      f("signboardSize", "看板尺寸", "layout", "看板實際寬度與高度尺寸是多少？"),
      f("signboardOrientation", "看板方向", "layout", "橫式還是直式？"),
      f("viewingDistance", "觀看距離", "layout", "主要觀看距離是什麼？例如遠距離車流或近距離行人。", false),
      f("safeArea", "安全範圍", "layout", "文字與重要元素是否需要預留安全距離？", false),
      f("bleedNeed", "出血需求", "layout", "輸出是否需要預留出血？", false),
      f("installHeight", "安裝高度", "environment", "看板距離地面的高度是多少？", false),
      f("viewingDirection", "觀看方向", "environment", "主要觀看角度或車流方向是什麼？", false),
      f("sitePhoto", "現場照片", "environment", "是否提供現場照片或街景圖？", false),
      f("mockupNeed", "模擬合成圖", "environment", "是否需要製作看板合成示意圖？", false),
      f("surroundings", "周圍環境", "environment", "是否有建築物、招牌或遮蔽物影響視覺？", false),
      f("outputMaterial", "輸出材質", "output", "輸出材質是什麼？例如帆布、貼圖、鋁板或燈箱布。", false),
      f("backlitNeed", "是否背光", "output", "是否為燈箱或需要夜間照明？", false),
      f("weatherproofNeed", "耐候需求", "output", "是否需要抗 UV 或防水材質？", false),
      f("outputHelp", "是否需要協助輸出", "output", "是否需要協助印刷與製作？", false),
      f("installationHelp", "是否需要施工", "output", "是否需要協助現場安裝？", false),
      f("useDate", "使用日期", "delivery", "看板開始使用時間是什麼時候？", false),
      f("deadline", "交稿期限", "delivery", "設計完成時間是什麼時候？", false),
      f("fileFormat", "檔案格式", "delivery", "是否需要提供印刷檔或施工圖檔？", false),
    ],
  },
  [DesignTaskType.store_sign]: {
    taskType: DesignTaskType.store_sign,
    displayName: "招牌設計",
    description: "收集招牌基本店家資訊、安裝位置、內容、風格、形式、尺寸與製作安裝需求。",
    keywords: ["招牌", "店面招牌", "門市招牌", "store sign"],
    starters: ["招牌設計"],
    sharedContextKeys: ["brandName", "logoFile", "brandColor"],
    fields: [
      f("storeName", "店家名稱", "basic", "店鋪或品牌名稱是什麼？"),
      f("storeType", "店家類型", "basic", "店家類型是什麼？例如餐廳、咖啡店、美容店、診所。"),
      f("storeAddress", "店面地址", "basic", "實際店面位置在哪裡？"),
      f("usageScenario", "使用情境", "basic", "使用情境是什麼？例如門市外牆招牌、騎樓招牌、側掛招牌。"),
      f("isNewStore", "是否為新店開幕", "basic", "是新開店還是舊店重新設計？"),
      f("installPosition", "安裝位置", "position", "招牌安裝的位置在哪裡？例如門面上方、騎樓外牆、側邊牆面。"),
      f("availableSpace", "可用空間", "position", "牆面可使用的寬度與高度是多少？"),
      f("viewingDirection", "觀看方向", "position", "招牌主要給哪個方向的人看？例如正面、側邊、街道車流。"),
      f("surroundings", "周邊環境", "position", "周圍是否有其他招牌或遮擋物？", false),
      f("sitePhoto", "現場照片", "position", "是否有現場照片可提供，並框出招牌位置？", false),
      f("signText", "招牌文字", "content", "需要放的店名或品牌名稱是什麼？"),
      f("subText", "副標文字", "content", "是否需要放服務項目、產品名稱或簡短介紹？", false),
      f("brandLogo", "品牌Logo", "content", "是否需要放品牌 Logo？", false),
      f("slogan", "標語或Slogan", "content", "是否需要品牌標語？", false),
      f("businessInfo", "營業資訊", "content", "是否需要放營業時間或聯絡方式？", false),
      f("stylePreference", "設計風格", "style", "希望招牌呈現什麼風格？例如簡約、復古、日系、現代。"),
      f("brandColor", "品牌顏色", "style", "是否有指定品牌顏色？", false),
      f("referenceCases", "參考案例", "style", "是否有喜歡或不喜歡的招牌風格？", false),
      f("brandVisual", "品牌視覺", "style", "是否需要符合品牌識別系統？", false),
      f("signType", "招牌類型", "form", "招牌類型是什麼？例如燈箱招牌、立體字招牌、壓克力招牌、金屬字招牌。"),
      f("lightNeed", "是否需要發光", "form", "是否需要內發光或背發光效果？", false),
      f("threeDTextNeed", "是否需要立體字", "form", "是否需要立體 Logo 或立體文字？", false),
      f("lightingEffect", "是否需要燈光效果", "form", "是否需要燈條或投射燈？", false),
      f("signSize", "招牌尺寸", "layout", "招牌實際寬度與高度是多少？"),
      f("signRatio", "招牌比例", "layout", "橫式還是直式？"),
      f("buildingLimit", "是否有建築限制", "layout", "建物外牆或店面是否有限制尺寸？", false),
      f("governmentRegulation", "是否有政府規範", "layout", "是否需要符合當地招牌法規？", false),
      f("logoFile", "Logo檔案", "assets", "品牌 Logo 是否提供？", false),
      f("brandGraphics", "品牌圖形", "assets", "是否有品牌圖騰或設計元素？", false),
      f("productImages", "圖片素材", "assets", "是否需要放產品圖片？", false),
      f("storePhotos", "店面照片", "assets", "是否提供店面現場照片以利設計模擬？", false),
      f("fabricationHelp", "是否需要協助製作", "production", "是否需要協助招牌製作？", false),
      f("siteMeasurement", "是否需要現場丈量", "production", "是否需要到現場丈量尺寸？", false),
      f("installationHelp", "是否需要安裝", "production", "是否需要招牌安裝服務？", false),
      f("openingDate", "開幕時間", "delivery", "店面開幕或使用日期是什麼時候？", false),
      f("designDeadline", "設計完成期限", "delivery", "設計需要完成的時間是什麼時候？", false),
      f("productionTime", "製作時間", "delivery", "是否需要預留招牌製作時間？", false),
      f("urgentNeed", "是否為急件", "delivery", "是否為急件設計或製作？", false),
    ],
  },
  [DesignTaskType.merchandise]: {
    taskType: DesignTaskType.merchandise,
    displayName: "周邊製作物設計",
    description: "收集周邊製作物（圍裙、衣服、帽子、袋子等穿用物件）的品牌資訊、產品類型、設計內容、規格與製作需求。",
    keywords: ["周邊", "圍裙", "衣服", "T-shirt", "帽子", "袋子", "帆布袋", "制服", "merchandise"],
    starters: ["周邊製作物設計", "制服設計", "帆布袋設計"],
    sharedContextKeys: ["brandName", "logoFile", "brandColor"],
    fields: [
      f("brandName", "品牌名稱", "basic", "品牌或店鋪名稱是什麼？"),
      f("brandType", "品牌類型", "basic", "品牌類型是什麼？例如餐廳、咖啡店、活動品牌、公司。"),
      f("usageScenario", "使用情境", "basic", "使用情境是什麼？例如門市制服、活動使用、販售商品、贈品。"),
      f("isEventUse", "是否為活動使用", "basic", "是短期活動還是長期使用？", false),
      f("brandPositioning", "品牌定位", "basic", "風格偏向是什麼？例如正式、活潑、文青、潮流。"),
      f("productItem", "製作項目", "product", "製作項目是什麼？圍裙、T-shirt、帽子、帆布袋或其他。"),
      f("targetUser", "使用對象", "product", "使用對象是誰？員工、客戶還是活動參與者。"),
      f("usageMethod", "使用方式", "product", "使用方式是什麼？日常穿著、活動穿著還是販售商品。"),
      f("multiDesignNeed", "是否需多款設計", "product", "是否有不同款式或版本？", false),
      f("mainGraphic", "主要圖案", "design", "需要呈現的圖像是什麼？Logo、插畫還是文字。"),
      f("textContent", "文字內容", "design", "是否有標語、店名、活動名稱等文字？", false),
      f("printPosition", "設計位置", "design", "印在哪裡？胸前、背面、袖子、帽前、袋子正面等。"),
      f("printSides", "版面數量", "design", "單面、雙面還是多位置設計？"),
      f("keyVisualExtension", "是否需要延伸主視覺", "design", "是否已有主視覺需套用？", false),
      f("stylePreference", "設計風格", "style", "設計風格是什麼？簡約、日系、潮流、工業風、可愛。"),
      f("brandColor", "品牌顏色", "style", "是否有指定顏色？例如 Pantone 或 CMYK。", false),
      f("referenceCases", "參考案例", "style", "喜歡或不喜歡的風格有哪些？", false),
      f("brandGuideline", "是否需符合品牌識別", "style", "是否已有品牌規範？", false),
      f("productStyle", "商品款式", "specs", "商品款式是什麼？短袖、長袖、有帽、無帽、半身圍裙、全身圍裙等。"),
      f("productColor", "商品顏色", "specs", "衣服或布料底色是什麼？"),
      f("sizeRange", "尺寸區間", "specs", "尺寸範圍是什麼？S、M、L、XL、是否有童裝。"),
      f("quantity", "數量", "specs", "每款預計製作數量是多少？"),
      f("material", "材質", "specs", "材質是什麼？棉、聚酯纖維、帆布等。", false),
      f("printMethod", "印刷方式", "printing", "印刷方式是什麼？網版印刷、熱轉印、刺繡、燙印。", false),
      f("colorCount", "顏色數量", "printing", "單色、多色還是漸層？", false),
      f("printLimitation", "是否有限制", "printing", "是否有限制？例如不能細線、不能漸層。", false),
      f("threeDEffect", "是否需要立體效果", "printing", "是否需要刺繡或厚版印刷？", false),
      f("logoFile", "Logo檔案", "assets", "品牌 Logo 是否提供？格式為 AI、SVG 或 PNG。", false),
      f("brandGraphics", "品牌圖形", "assets", "是否有圖騰或插畫素材？", false),
      f("textAssets", "文字內容", "assets", "是否有可複製的文字？", false),
      f("referenceImages", "參考圖片", "assets", "是否有喜歡的設計案例圖片？", false),
      f("sampleNeed", "是否需要打樣", "production", "是否需先做樣品確認？", false),
      f("productionHelp", "是否需協助製作", "production", "是否由設計方協助找廠商？", false),
      f("printConfirmation", "是否需確認印刷效果", "production", "是否需要確認顏色、位置與材質？", false),
      f("useDate", "使用時間", "delivery", "活動或上線日期是什麼時候？", false),
      f("designDeadline", "設計完成期限", "delivery", "何時需交稿？何時要拿到實品？", false),
    ],
  },
  [DesignTaskType.gift]: {
    taskType: DesignTaskType.gift,
    displayName: "禮贈品設計",
    description: "收集禮贈品設計需求、品牌資訊、品項、風格與製作交付需求。",
    keywords: ["禮贈品", "贈品", "紀念品", "gift", "禮品設計"],
    starters: ["禮贈品設計", "贈品設計"],
    sharedContextKeys: ["brandName", "logoFile", "brandColor"],
    fields: [
      f("brandName", "品牌名稱", "basic", "品牌或公司名稱是什麼？"),
      f("giftPurpose", "贈品用途", "basic", "禮贈品主要用途是什麼？例如活動贈品、客戶禮品、員工獎品。"),
      f("giftItems", "贈品品項", "basic", "預計製作的品項有哪些？"),
      f("targetRecipient", "贈送對象", "basic", "主要贈送對象是誰？"),
      f("stylePreference", "設計風格", "style", "希望贈品呈現什麼風格？"),
      f("brandColor", "品牌顏色", "style", "是否有指定品牌顏色？", false),
      f("referenceCases", "參考案例", "style", "是否有喜歡的贈品設計參考？", false),
      f("logoFile", "Logo檔案", "assets", "品牌 Logo 是否提供？", false),
      f("quantity", "製作數量", "specs", "每款預計製作多少？", false),
      f("budget", "預算範圍", "specs", "每個贈品的預算範圍是多少？", false),
      f("useDate", "使用時間", "delivery", "贈品預計何時需要使用？", false),
      f("deadline", "交稿期限", "delivery", "設計需要完成的時間是什麼時候？", false),
      f("productionHelp", "是否需協助製作", "delivery", "是否需要協助找廠商製作？", false),
    ],
  },
  [DesignTaskType.illustration]: {
    taskType: DesignTaskType.illustration,
    displayName: "插畫設計",
    description: "收集插畫設計需求，涵蓋品牌插畫、產品插畫、書籍插畫、角色設計、吉祥物設計、社群插畫、包裝插畫、貼圖設計等。",
    keywords: ["插畫", "illustration", "角色設計", "吉祥物", "貼圖", "品牌插畫", "產品插畫", "書籍插畫", "社群插畫", "包裝插畫"],
    starters: ["插畫設計", "角色設計", "吉祥物設計", "貼圖設計"],
    sharedContextKeys: ["brandName", "logoFile", "brandColor"],
    fields: [
      f("illustrationContent", "插畫內容", "content", "需要繪製的內容是什麼？"),
      f("illustrationType", "插畫類型", "basic", "這次比較偏哪一種插畫需求？例如角色設計、吉祥物、品牌插畫、貼圖或包裝插畫。"),
      f("purpose", "用途", "basic", "這張插畫主要想拿來做什麼？"),
      f("usageScenario", "使用場景", "basic", "這張插畫之後會用在哪裡？例如社群、網站、包裝、書籍、LINE 貼圖。"),
      f("targetAudience", "目標客群", "basic", "這張插畫主要是想給誰看的？"),
      f("characterDescription", "角色描述", "content", "若為角色或吉祥物設計，角色的個性、外型特徵是什麼？", false),
      f("quantity", "插畫數量", "content", "需要幾張插畫或幾個角色？"),
      f("textNeed", "是否需要搭配文字", "content", "插畫是否需要搭配文字？", false),
      f("stylePreference", "設計風格", "style", "希望插畫呈現什麼風格？例如手繪、扁平、日系、可愛、寫實。"),
      f("colorPreference", "顏色偏好", "style", "是否有指定顏色或品牌色？", false),
      f("referenceCases", "參考案例", "style", "是否有喜歡或不喜歡的插畫風格？", false),
      f("brandTone", "品牌調性", "style", "插畫需要符合什麼品牌調性？", false),
      f("brandName", "品牌名稱", "basic", "如果這張插畫和品牌有關，品牌或公司名稱是什麼？", false),
      f("logoFile", "Logo檔案", "assets", "品牌 Logo 是否提供？", false),
      f("referenceImages", "參考素材", "assets", "是否有參考圖片或素材？", false),
      f("deliverySize", "交付尺寸", "delivery", "插畫交付尺寸是多少？", false),
      f("fileFormat", "檔案格式", "delivery", "需要什麼格式？例如 AI、PSD、PNG、SVG。", false),
      f("deadline", "交稿期限", "delivery", "設計需要完成的時間是什麼時候？", false),
    ],
  },
  [DesignTaskType.design_modification]: {
    taskType: DesignTaskType.design_modification,
    displayName: "修改服務",
    description: "收集舊設計修改、圖片去背、圖片修圖、尺寸調整、檔案轉檔等修改服務需求。",
    keywords: ["修改", "去背", "修圖", "尺寸調整", "resize", "轉檔", "舊設計修改", "BN resize"],
    starters: ["設計修改", "圖片去背", "圖片修圖", "尺寸調整", "檔案轉檔"],
    fields: [
      f("modificationScope", "修改類型", "basic", "需要什麼修改服務？例如舊設計修改、圖片去背、圖片修圖、尺寸調整（BN resize）、檔案轉檔。"),
      f("originalFile", "原始檔案", "basic", "是否有提供原始設計檔案？"),
      f("modificationDetail", "修改內容", "basic", "具體需要修改的內容是什麼？"),
      f("outputFormat", "輸出格式", "basic", "修改後需要什麼格式？", false),
      f("outputSize", "輸出尺寸", "basic", "修改後需要什麼尺寸？", false),
      f("quantity", "修改數量", "basic", "需要修改幾張或幾個檔案？"),
      f("deadline", "交稿期限", "delivery", "需要完成的時間是什麼時候？", false),
      f("urgentNeed", "是否為急件", "delivery", "是否為急件？", false),
    ],
  },
  [DesignTaskType.social_copy]: {
    taskType: DesignTaskType.social_copy,
    displayName: "社群文案",
    description: "依社群平台特性、品牌資訊、主題、目標與語氣整理社群文案需求，並產出對應平台文案。",
    keywords: ["社群文案", "文案", "instagram文案", "facebook文案", "threads文案", "linkedin文案", "line oa文案"],
    starters: ["社群文案", "幫我寫社群文案", "社群貼文文案"],
    sharedContextKeys: ["brandName", "industry", "brandPersonality", "targetAudience"],
    minimumViableRequirementKeys: ["brandName", "platform", "contentTheme", "marketingGoal", "coreMessage"],
    minimumViableThreshold: 4,
    fields: [
      f("brandName", "品牌名稱", "basic", "品牌或公司名稱是什麼？"),
      f("industry", "品牌產業", "basic", "品牌所屬產業是什麼？", false),
      f("brandPersonality", "品牌個性", "basic", "品牌給人的感覺是什麼？例如專業、創新。", false),
      f("targetAudience", "目標客群", "basic", "主要客戶族群是誰？", false),
      f("platform", "發布平台", "platform", "這篇文案主要要發布在哪個社群平台？例如 Instagram、Facebook、Threads、LinkedIn、Line OA。"),
      f("contentTheme", "內容主題", "content", "這篇貼文主要想講什麼主題？"),
      f("marketingGoal", "行銷目標", "content", "這篇貼文最主要的目的是什麼？例如提高互動、品牌曝光、導購。"),
      f("toneOfVoice", "文案語氣", "style", "希望文案語氣偏什麼風格？例如活潑、專業、故事感。", false),
      f("coreMessage", "核心訊息", "content", "最想讓讀者記住的重點是什麼？"),
      f("cta", "行動呼籲", "content", "希望讀者看到後做什麼？例如留言分享、點擊連結。", false),
    ],
  },
  [DesignTaskType.seo_article]: {
    taskType: DesignTaskType.seo_article,
    displayName: "SEO文章",
    description: "收集 SEO 文章所需的品牌、產品、關鍵字、目標頁、文章方向與 CTA，產出 SEO 架構與內容。",
    keywords: ["seo文章", "seo", "部落格文章", "導購文", "關鍵字文章"],
    starters: ["SEO文章", "幫我寫SEO文章"],
    sharedContextKeys: ["brandName", "industry", "targetAudience", "website"],
    minimumViableRequirementKeys: ["brandName", "promotedProduct", "seoGoal", "articleTopic", "articleType"],
    minimumViableThreshold: 4,
    fields: [
      f("brandName", "品牌名稱", "basic", "品牌或公司名稱是什麼？"),
      f("industry", "品牌產業 / 服務類別", "basic", "品牌所屬產業或服務類別是什麼？", false),
      f("promotedProduct", "想推廣的產品或服務", "basic", "這篇 SEO 文章主要想推廣哪個產品或服務？"),
      f("targetAudience", "目標客群", "basic", "主要客戶族群是誰？", false),
      f("seoGoal", "SEO目標", "goal", "這篇文章希望達到什麼 SEO 目標？例如提升搜尋排名、增加流量、導購。"),
      f("targetPageUrl", "目標頁面 URL", "goal", "文章希望導向哪個產品頁或品牌頁？", false),
      f("primaryKeywords", "主要關鍵字", "keywords", "如果已有主要關鍵字，請直接提供；若沒有，我也可以先幫你建議。", false),
      f("secondaryKeywords", "次要關鍵字", "keywords", "如果已有次要關鍵字，也可以一起提供。", false),
      f("articleTopic", "文章主題或方向", "content", "這篇文章想討論的核心主題是什麼？"),
      f("articleType", "文章類型", "content", "這篇要做部落格文章、商品頁、FAQ，還是導購文？"),
      f("contentLength", "預期字數", "content", "希望是短篇、中篇還是長篇？", false),
      f("toneOfVoice", "語氣與風格", "style", "希望文章語氣偏專業、活潑，還是生活化？", false),
      f("cta", "CTA", "content", "希望讀者最後做什麼？例如點擊購買、留言分享。", false),
      f("competitorReferences", "競爭對手參考", "reference", "是否有競爭品牌或網站案例可以參考？", false),
      f("extraSeoRequirements", "額外要求", "reference", "是否有特別要注意的 SEO 需求、排版、內部鏈接或長尾關鍵字使用？", false),
    ],
  },
  [DesignTaskType.website_audit]: {
    taskType: DesignTaskType.website_audit,
    displayName: "網站健檢",
    description: "收集網站 SEO 健檢所需的品牌、網址、主要頁面、關鍵字與技術現況，輸出分區塊報告。",
    keywords: ["網站健檢", "seo健檢", "網站分析", "網站seo", "website audit"],
    starters: ["網站健檢", "SEO網站健檢"],
    sharedContextKeys: ["brandName", "industry", "website"],
    minimumViableRequirementKeys: ["brandName", "industry", "websiteUrl", "primaryPages"],
    minimumViableThreshold: 4,
    fields: [
      f("brandName", "品牌 / 公司資訊", "basic", "品牌或公司名稱是什麼？"),
      f("industry", "產業或主要服務類別", "basic", "主要產業或服務類別是什麼？"),
      f("mainProducts", "主要產品或服務", "basic", "主要產品或服務有哪些？", false),
      f("targetAudience", "目標客群", "basic", "目標客群是誰？", false),
      f("websiteUrl", "網站 URL", "website", "要健檢的網站 URL 是什麼？"),
      f("primaryPages", "主要頁面", "website", "這次想重點看的主要頁面有哪些？例如首頁、產品頁、品牌故事頁。"),
      f("httpsEnabled", "是否啟用 HTTPS", "technical", "網站目前是否已啟用 HTTPS？", false),
      f("titleMeta", "Title 與 Meta Description", "technical", "主要頁面的 Title 與 Meta Description 目前大致是什麼？", false),
      f("keywordPlan", "主要 / 次要關鍵字", "content", "目前有鎖定哪些主要或次要關鍵字嗎？若沒有我可以先幫你推估。", false),
      f("linkOverview", "內外部連結概況", "link", "目前網站的內部或外部連結概況如何？", false),
      f("performanceStatus", "網站速度 / 手機友善度", "ux", "網站速度與手機版友善度目前大致如何？", false),
    ],
  },
  [DesignTaskType.annual_marketing_strategy]: {
    taskType: DesignTaskType.annual_marketing_strategy,
    displayName: "整年度行銷策略",
    description: "收集品牌、產品、目標客群、競品、活動節點、預算與渠道偏好，輸出年度策略與季度拆解。",
    keywords: ["年度行銷策略", "行銷策略", "年度策略", "全年行銷", "marketing strategy"],
    starters: ["整年度行銷策略", "年度行銷規劃"],
    sharedContextKeys: ["brandName", "industry", "targetAudience", "budget"],
    minimumViableRequirementKeys: ["brandName", "promotedProduct", "targetAudience", "marketingGoal", "monthlyBudget"],
    minimumViableThreshold: 5,
    fields: [
      f("brandName", "品牌名稱", "basic", "品牌或公司名稱是什麼？"),
      f("industry", "品牌產業 / 服務類別", "basic", "品牌所屬產業或服務類別是什麼？"),
      f("promotedProduct", "想推廣的產品或服務", "basic", "今年主要想推廣哪些產品或服務？"),
      f("targetAudience", "目標客群", "basic", "主要客戶族群是誰？可包含年齡、性別、痛點。"),
      f("competitors", "主要競爭對手品牌", "basic", "主要競爭對手有哪些？", false),
      f("campaignMoments", "期待的年度活動節點", "timeline", "今年一定要跟的節點有哪些？例如雙11、母親節、夏季促銷。", false),
      f("brandTone", "品牌核心價值與調性", "basic", "品牌重視的理念與整體感覺是什麼？"),
      f("marketingGoal", "行銷核心目標", "goal", "今年最重要的成果指標是什麼？"),
      f("shortTermGoal", "短期目標", "goal", "接下來 1–3 個月希望達到什麼可量化目標？", false),
      f("midLongTermGoal", "中長期目標", "goal", "6–12 個月的中長期目標是什麼？", false),
      f("pricingPromo", "產品售價範圍 / 促銷活動", "basic", "產品價格帶與促銷方案大致如何？", false),
      f("monthlyBudget", "每月行銷預算", "budget", "每月大概可投入多少行銷預算？"),
      f("channels", "希望曝光的渠道", "channel", "主要想用哪些渠道？例如 SEO、社群、廣告、EDM、KOL。"),
      f("strategyPreference", "策略偏好", "channel", "偏好的行銷策略方向是什麼？例如內容行銷、SEO、廣告投放。", false),
      f("priorityStrategy", "資源有限時的優先策略", "channel", "如果資源有限，最想優先做哪 1～2 個策略？", false),
    ],
  },
  [DesignTaskType.ads_strategy]: {
    taskType: DesignTaskType.ads_strategy,
    displayName: "廣告投放策略",
    description: "收集品牌、產品、受眾、預算、KPI、追蹤工具與平台偏好，輸出廣告平台策略與預算分配建議。",
    keywords: ["廣告投放", "投放策略", "ads strategy", "廣告策略", "媒體投放"],
    starters: ["廣告投放策略", "廣告策略規劃"],
    sharedContextKeys: ["brandName", "industry", "targetAudience", "website"],
    minimumViableRequirementKeys: ["brandName", "promotedProduct", "targetAudience", "adGoal", "budgetTotal"],
    minimumViableThreshold: 5,
    fields: [
      f("clientCompany", "客戶企業 / 產業", "basic", "客戶企業或產業是什麼？", false),
      f("brandName", "品牌名稱", "basic", "品牌名稱是什麼？"),
      f("contactInfo", "聯繫方式", "basic", "聯繫方式是什麼？例如 email 或電話。", false),
      f("websiteUrl", "官網 / LP", "basic", "官網或 LP 網址是什麼？", false),
      f("industry", "品牌產業 / 服務類別", "basic", "品牌所屬產業或服務類別是什麼？"),
      f("promotedProduct", "想推廣的產品或服務", "basic", "透過廣告主要想推廣哪些產品或服務？"),
      f("averageOrderValue", "平均客單價", "basic", "平均客單價大概落在哪個區間？", false),
      f("brandPositioning", "品牌定位", "basic", "品牌定位偏高價、中高、中價還是平價？", false),
      f("marketRegion", "主要市場地區", "basic", "主要市場地區是哪裡？"),
      f("targetAudience", "目標客群", "audience", "主要客群是誰？可包含年齡、性別、需求或痛點。"),
      f("competitors", "主要競爭對手品牌", "audience", "主要競爭對手有哪些？", false),
      f("trackingSetup", "是否已有 GTM / GA4 / Facebook Pixel", "tracking", "目前有安裝 GTM、GA4 或 Facebook Pixel 嗎？", false),
      f("adGoal", "廣告投放目標", "goal", "廣告最主要目標是什麼？例如品牌曝光、網站流量、商品銷售。"),
      f("kpiTarget", "預期達到 KPI", "goal", "預期希望達到哪些 KPI？例如 CPA、CTR、CV。", false),
      f("budgetTotal", "廣告投放總預算", "budget", "總投放預算大概是多少？"),
      f("campaignDuration", "廣告投放期間", "budget", "預計投放多久？例如季度或半年。"),
      f("brandManual", "品牌 / 產品手冊", "assets", "若有品牌或產品手冊，也可以提供給我參考。", false),
    ],
  },
};
